// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: site.standard.graph.subscription

package standardsite

import (
	lexutil "github.com/bluesky-social/indigo/lex/util"
)

func init() {
	lexutil.RegisterType("site.standard.graph.subscription", &GraphSubscription{})
}

type GraphSubscription struct {
	LexiconTypeID string  `json:"$type" cborgen:"$type,const=site.standard.graph.subscription"`
	CreatedAt     *string `json:"createdAt,omitempty" cborgen:"createdAt,omitempty"`
	// publication: AT-URI reference to the publication record being subscribed to (ex: at://did:plc:abc123/site.standard.publication/xyz789).
	Publication string `json:"publication" cborgen:"publication"`
}
