// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: app.bsky.actor.link

package bsky

import (
	lexutil "github.com/bluesky-social/indigo/lex/util"
)

func init() {
	lexutil.RegisterType("app.bsky.actor.link", &ActorLink{})
}

type ActorLink struct {
	LexiconTypeID string `json:"$type" cborgen:"$type,const=app.bsky.actor.link"`
	CreatedAt     string `json:"createdAt" cborgen:"createdAt"`
	// icon: The destination site's icon, uploaded when the link is saved.
	Icon *lexutil.LexBlob `json:"icon,omitempty" cborgen:"icon,omitempty"`
	// title: Optional label for the link. Clients can fall back to the destination's domain.
	Title *string `json:"title,omitempty" cborgen:"title,omitempty"`
	// url: The link destination, an https URL.
	Url string `json:"url" cborgen:"url"`
}
