// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: app.bsky.ageassurance.getConfig

package bsky

import (
	"context"

	lexutil "github.com/bluesky-social/indigo/lex/util"
)

// AgeassuranceGetConfig calls the XRPC method "app.bsky.ageassurance.getConfig".
func AgeassuranceGetConfig(ctx context.Context, c lexutil.LexClient) (*AgeassuranceDefs_Config, error) {
	var out AgeassuranceDefs_Config
	if err := c.LexDo(ctx, lexutil.Query, "", "app.bsky.ageassurance.getConfig", nil, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
