// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: app.bsky.ageassurance.defs

package bsky

import (
	"encoding/json"
	"fmt"

	lexutil "github.com/bluesky-social/indigo/lex/util"
)

// AgeassuranceDefs_Config is a "config" in the app.bsky.ageassurance.defs schema.
type AgeassuranceDefs_Config struct {
	// regions: The per-region Age Assurance configuration.
	Regions []*AgeassuranceDefs_ConfigRegion `json:"regions" cborgen:"regions"`
}

// AgeassuranceDefs_ConfigRegion is a "configRegion" in the app.bsky.ageassurance.defs schema.
//
// The Age Assurance configuration for a specific region.
type AgeassuranceDefs_ConfigRegion struct {
	// countryCode: The ISO 3166-1 alpha-2 country code this configuration applies to.
	CountryCode string `json:"countryCode" cborgen:"countryCode"`
	// regionCode: The ISO 3166-2 region code this configuration applies to. If omitted, the configuration applies to the entire country.
	RegionCode *string `json:"regionCode,omitempty" cborgen:"regionCode,omitempty"`
	// rules: The ordered list of Age Assurance rules that apply to this region. Rules should be applied in order, and the first matching rule determines the access level granted. The rules array should always include a default rule as the last item.
	Rules []*AgeassuranceDefs_ConfigRegion_Rules_Elem `json:"rules" cborgen:"rules"`
}

// AgeassuranceDefs_ConfigRegionRuleDefault is a "configRegionRuleDefault" in the app.bsky.ageassurance.defs schema.
//
// Age Assurance rule that applies by default.
type AgeassuranceDefs_ConfigRegionRuleDefault struct {
	LexiconTypeID string  `json:"$type" cborgen:"$type,const=app.bsky.ageassurance.defs#configRegionRuleDefault"`
	Access        *string `json:"access" cborgen:"access"`
}

// AgeassuranceDefs_ConfigRegionRuleIfAccountNewerThan is a "configRegionRuleIfAccountNewerThan" in the app.bsky.ageassurance.defs schema.
//
// Age Assurance rule that applies if the account is equal-to or newer than a certain date.
type AgeassuranceDefs_ConfigRegionRuleIfAccountNewerThan struct {
	LexiconTypeID string  `json:"$type" cborgen:"$type,const=app.bsky.ageassurance.defs#configRegionRuleIfAccountNewerThan"`
	Access        *string `json:"access" cborgen:"access"`
	// date: The date threshold as a datetime string.
	Date string `json:"date" cborgen:"date"`
}

// AgeassuranceDefs_ConfigRegionRuleIfAccountOlderThan is a "configRegionRuleIfAccountOlderThan" in the app.bsky.ageassurance.defs schema.
//
// Age Assurance rule that applies if the account is older than a certain date.
type AgeassuranceDefs_ConfigRegionRuleIfAccountOlderThan struct {
	LexiconTypeID string  `json:"$type" cborgen:"$type,const=app.bsky.ageassurance.defs#configRegionRuleIfAccountOlderThan"`
	Access        *string `json:"access" cborgen:"access"`
	// date: The date threshold as a datetime string.
	Date string `json:"date" cborgen:"date"`
}

// AgeassuranceDefs_ConfigRegionRuleIfAssuredOverAge is a "configRegionRuleIfAssuredOverAge" in the app.bsky.ageassurance.defs schema.
//
// Age Assurance rule that applies if the user has been assured to be equal-to or over a certain age.
type AgeassuranceDefs_ConfigRegionRuleIfAssuredOverAge struct {
	LexiconTypeID string  `json:"$type" cborgen:"$type,const=app.bsky.ageassurance.defs#configRegionRuleIfAssuredOverAge"`
	Access        *string `json:"access" cborgen:"access"`
	// age: The age threshold as a whole integer.
	Age int64 `json:"age" cborgen:"age"`
}

// AgeassuranceDefs_ConfigRegionRuleIfAssuredUnderAge is a "configRegionRuleIfAssuredUnderAge" in the app.bsky.ageassurance.defs schema.
//
// Age Assurance rule that applies if the user has been assured to be under a certain age.
type AgeassuranceDefs_ConfigRegionRuleIfAssuredUnderAge struct {
	LexiconTypeID string  `json:"$type" cborgen:"$type,const=app.bsky.ageassurance.defs#configRegionRuleIfAssuredUnderAge"`
	Access        *string `json:"access" cborgen:"access"`
	// age: The age threshold as a whole integer.
	Age int64 `json:"age" cborgen:"age"`
}

// AgeassuranceDefs_ConfigRegionRuleIfDeclaredOverAge is a "configRegionRuleIfDeclaredOverAge" in the app.bsky.ageassurance.defs schema.
//
// Age Assurance rule that applies if the user has declared themselves equal-to or over a certain age.
type AgeassuranceDefs_ConfigRegionRuleIfDeclaredOverAge struct {
	LexiconTypeID string  `json:"$type" cborgen:"$type,const=app.bsky.ageassurance.defs#configRegionRuleIfDeclaredOverAge"`
	Access        *string `json:"access" cborgen:"access"`
	// age: The age threshold as a whole integer.
	Age int64 `json:"age" cborgen:"age"`
}

// AgeassuranceDefs_ConfigRegionRuleIfDeclaredUnderAge is a "configRegionRuleIfDeclaredUnderAge" in the app.bsky.ageassurance.defs schema.
//
// Age Assurance rule that applies if the user has declared themselves under a certain age.
type AgeassuranceDefs_ConfigRegionRuleIfDeclaredUnderAge struct {
	LexiconTypeID string  `json:"$type" cborgen:"$type,const=app.bsky.ageassurance.defs#configRegionRuleIfDeclaredUnderAge"`
	Access        *string `json:"access" cborgen:"access"`
	// age: The age threshold as a whole integer.
	Age int64 `json:"age" cborgen:"age"`
}

type AgeassuranceDefs_ConfigRegion_Rules_Elem struct {
	AgeassuranceDefs_ConfigRegionRuleDefault            *AgeassuranceDefs_ConfigRegionRuleDefault
	AgeassuranceDefs_ConfigRegionRuleIfDeclaredOverAge  *AgeassuranceDefs_ConfigRegionRuleIfDeclaredOverAge
	AgeassuranceDefs_ConfigRegionRuleIfDeclaredUnderAge *AgeassuranceDefs_ConfigRegionRuleIfDeclaredUnderAge
	AgeassuranceDefs_ConfigRegionRuleIfAssuredOverAge   *AgeassuranceDefs_ConfigRegionRuleIfAssuredOverAge
	AgeassuranceDefs_ConfigRegionRuleIfAssuredUnderAge  *AgeassuranceDefs_ConfigRegionRuleIfAssuredUnderAge
	AgeassuranceDefs_ConfigRegionRuleIfAccountNewerThan *AgeassuranceDefs_ConfigRegionRuleIfAccountNewerThan
	AgeassuranceDefs_ConfigRegionRuleIfAccountOlderThan *AgeassuranceDefs_ConfigRegionRuleIfAccountOlderThan
}

func (t *AgeassuranceDefs_ConfigRegion_Rules_Elem) MarshalJSON() ([]byte, error) {
	if t.AgeassuranceDefs_ConfigRegionRuleDefault != nil {
		t.AgeassuranceDefs_ConfigRegionRuleDefault.LexiconTypeID = "app.bsky.ageassurance.defs#configRegionRuleDefault"
		return json.Marshal(t.AgeassuranceDefs_ConfigRegionRuleDefault)
	}
	if t.AgeassuranceDefs_ConfigRegionRuleIfDeclaredOverAge != nil {
		t.AgeassuranceDefs_ConfigRegionRuleIfDeclaredOverAge.LexiconTypeID = "app.bsky.ageassurance.defs#configRegionRuleIfDeclaredOverAge"
		return json.Marshal(t.AgeassuranceDefs_ConfigRegionRuleIfDeclaredOverAge)
	}
	if t.AgeassuranceDefs_ConfigRegionRuleIfDeclaredUnderAge != nil {
		t.AgeassuranceDefs_ConfigRegionRuleIfDeclaredUnderAge.LexiconTypeID = "app.bsky.ageassurance.defs#configRegionRuleIfDeclaredUnderAge"
		return json.Marshal(t.AgeassuranceDefs_ConfigRegionRuleIfDeclaredUnderAge)
	}
	if t.AgeassuranceDefs_ConfigRegionRuleIfAssuredOverAge != nil {
		t.AgeassuranceDefs_ConfigRegionRuleIfAssuredOverAge.LexiconTypeID = "app.bsky.ageassurance.defs#configRegionRuleIfAssuredOverAge"
		return json.Marshal(t.AgeassuranceDefs_ConfigRegionRuleIfAssuredOverAge)
	}
	if t.AgeassuranceDefs_ConfigRegionRuleIfAssuredUnderAge != nil {
		t.AgeassuranceDefs_ConfigRegionRuleIfAssuredUnderAge.LexiconTypeID = "app.bsky.ageassurance.defs#configRegionRuleIfAssuredUnderAge"
		return json.Marshal(t.AgeassuranceDefs_ConfigRegionRuleIfAssuredUnderAge)
	}
	if t.AgeassuranceDefs_ConfigRegionRuleIfAccountNewerThan != nil {
		t.AgeassuranceDefs_ConfigRegionRuleIfAccountNewerThan.LexiconTypeID = "app.bsky.ageassurance.defs#configRegionRuleIfAccountNewerThan"
		return json.Marshal(t.AgeassuranceDefs_ConfigRegionRuleIfAccountNewerThan)
	}
	if t.AgeassuranceDefs_ConfigRegionRuleIfAccountOlderThan != nil {
		t.AgeassuranceDefs_ConfigRegionRuleIfAccountOlderThan.LexiconTypeID = "app.bsky.ageassurance.defs#configRegionRuleIfAccountOlderThan"
		return json.Marshal(t.AgeassuranceDefs_ConfigRegionRuleIfAccountOlderThan)
	}
	return nil, fmt.Errorf("can not marshal empty union as JSON")
}

func (t *AgeassuranceDefs_ConfigRegion_Rules_Elem) UnmarshalJSON(b []byte) error {
	typ, err := lexutil.TypeExtract(b)
	if err != nil {
		return err
	}

	switch typ {
	case "app.bsky.ageassurance.defs#configRegionRuleDefault":
		t.AgeassuranceDefs_ConfigRegionRuleDefault = new(AgeassuranceDefs_ConfigRegionRuleDefault)
		return json.Unmarshal(b, t.AgeassuranceDefs_ConfigRegionRuleDefault)
	case "app.bsky.ageassurance.defs#configRegionRuleIfDeclaredOverAge":
		t.AgeassuranceDefs_ConfigRegionRuleIfDeclaredOverAge = new(AgeassuranceDefs_ConfigRegionRuleIfDeclaredOverAge)
		return json.Unmarshal(b, t.AgeassuranceDefs_ConfigRegionRuleIfDeclaredOverAge)
	case "app.bsky.ageassurance.defs#configRegionRuleIfDeclaredUnderAge":
		t.AgeassuranceDefs_ConfigRegionRuleIfDeclaredUnderAge = new(AgeassuranceDefs_ConfigRegionRuleIfDeclaredUnderAge)
		return json.Unmarshal(b, t.AgeassuranceDefs_ConfigRegionRuleIfDeclaredUnderAge)
	case "app.bsky.ageassurance.defs#configRegionRuleIfAssuredOverAge":
		t.AgeassuranceDefs_ConfigRegionRuleIfAssuredOverAge = new(AgeassuranceDefs_ConfigRegionRuleIfAssuredOverAge)
		return json.Unmarshal(b, t.AgeassuranceDefs_ConfigRegionRuleIfAssuredOverAge)
	case "app.bsky.ageassurance.defs#configRegionRuleIfAssuredUnderAge":
		t.AgeassuranceDefs_ConfigRegionRuleIfAssuredUnderAge = new(AgeassuranceDefs_ConfigRegionRuleIfAssuredUnderAge)
		return json.Unmarshal(b, t.AgeassuranceDefs_ConfigRegionRuleIfAssuredUnderAge)
	case "app.bsky.ageassurance.defs#configRegionRuleIfAccountNewerThan":
		t.AgeassuranceDefs_ConfigRegionRuleIfAccountNewerThan = new(AgeassuranceDefs_ConfigRegionRuleIfAccountNewerThan)
		return json.Unmarshal(b, t.AgeassuranceDefs_ConfigRegionRuleIfAccountNewerThan)
	case "app.bsky.ageassurance.defs#configRegionRuleIfAccountOlderThan":
		t.AgeassuranceDefs_ConfigRegionRuleIfAccountOlderThan = new(AgeassuranceDefs_ConfigRegionRuleIfAccountOlderThan)
		return json.Unmarshal(b, t.AgeassuranceDefs_ConfigRegionRuleIfAccountOlderThan)
	default:
		return nil
	}
}

// AgeassuranceDefs_Event is a "event" in the app.bsky.ageassurance.defs schema.
//
// Object used to store Age Assurance data in stash.
type AgeassuranceDefs_Event struct {
	// access: The access level granted based on Age Assurance data we've processed.
	Access string `json:"access" cborgen:"access"`
	// attemptId: The unique identifier for this instance of the Age Assurance flow, in UUID format.
	AttemptId string `json:"attemptId" cborgen:"attemptId"`
	// completeIp: The IP address used when completing the Age Assurance flow.
	CompleteIp *string `json:"completeIp,omitempty" cborgen:"completeIp,omitempty"`
	// completeUa: The user agent used when completing the Age Assurance flow.
	CompleteUa *string `json:"completeUa,omitempty" cborgen:"completeUa,omitempty"`
	// countryCode: The ISO 3166-1 alpha-2 country code provided when beginning the Age Assurance flow.
	CountryCode string `json:"countryCode" cborgen:"countryCode"`
	// createdAt: The date and time of this write operation.
	CreatedAt string `json:"createdAt" cborgen:"createdAt"`
	// email: The email used for Age Assurance.
	Email *string `json:"email,omitempty" cborgen:"email,omitempty"`
	// initIp: The IP address used when initiating the Age Assurance flow.
	InitIp *string `json:"initIp,omitempty" cborgen:"initIp,omitempty"`
	// initUa: The user agent used when initiating the Age Assurance flow.
	InitUa *string `json:"initUa,omitempty" cborgen:"initUa,omitempty"`
	// regionCode: The ISO 3166-2 region code provided when beginning the Age Assurance flow.
	RegionCode *string `json:"regionCode,omitempty" cborgen:"regionCode,omitempty"`
	// status: The status of the Age Assurance process.
	Status string `json:"status" cborgen:"status"`
}

// AgeassuranceDefs_State is a "state" in the app.bsky.ageassurance.defs schema.
//
// The user's computed Age Assurance state.
type AgeassuranceDefs_State struct {
	Access *string `json:"access" cborgen:"access"`
	// lastInitiatedAt: The timestamp when this state was last updated.
	LastInitiatedAt *string `json:"lastInitiatedAt,omitempty" cborgen:"lastInitiatedAt,omitempty"`
	Status          *string `json:"status" cborgen:"status"`
}

// AgeassuranceDefs_StateMetadata is a "stateMetadata" in the app.bsky.ageassurance.defs schema.
//
// Additional metadata needed to compute Age Assurance state client-side.
type AgeassuranceDefs_StateMetadata struct {
	// accountCreatedAt: The account creation timestamp.
	AccountCreatedAt *string `json:"accountCreatedAt,omitempty" cborgen:"accountCreatedAt,omitempty"`
}
