// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: app.bsky.contact.dismissMatch

package bsky

import (
	"context"

	lexutil "github.com/bluesky-social/indigo/lex/util"
)

// ContactDismissMatch_Input is the input argument to a app.bsky.contact.dismissMatch call.
type ContactDismissMatch_Input struct {
	// subject: The subject's DID to dismiss the match with.
	Subject string `json:"subject" cborgen:"subject"`
}

// ContactDismissMatch_Output is the output of a app.bsky.contact.dismissMatch call.
type ContactDismissMatch_Output struct {
}

// ContactDismissMatch calls the XRPC method "app.bsky.contact.dismissMatch".
func ContactDismissMatch(ctx context.Context, c lexutil.LexClient, input *ContactDismissMatch_Input) (*ContactDismissMatch_Output, error) {
	var out ContactDismissMatch_Output
	if err := c.LexDo(ctx, lexutil.Procedure, "application/json", "app.bsky.contact.dismissMatch", nil, input, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
