// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: app.bsky.contact.sendNotification

package bsky

import (
	"context"

	lexutil "github.com/bluesky-social/indigo/lex/util"
)

// ContactSendNotification_Input is the input argument to a app.bsky.contact.sendNotification call.
type ContactSendNotification_Input struct {
	// from: The DID of who this notification comes from.
	From string `json:"from" cborgen:"from"`
	// to: The DID of who this notification should go to.
	To string `json:"to" cborgen:"to"`
}

// ContactSendNotification_Output is the output of a app.bsky.contact.sendNotification call.
type ContactSendNotification_Output struct {
}

// ContactSendNotification calls the XRPC method "app.bsky.contact.sendNotification".
func ContactSendNotification(ctx context.Context, c lexutil.LexClient, input *ContactSendNotification_Input) (*ContactSendNotification_Output, error) {
	var out ContactSendNotification_Output
	if err := c.LexDo(ctx, lexutil.Procedure, "application/json", "app.bsky.contact.sendNotification", nil, input, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
