// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: app.bsky.feed.sendInteractions

package bsky

import (
	"context"

	lexutil "github.com/bluesky-social/indigo/lex/util"
)

// FeedSendInteractions_Input is the input argument to a app.bsky.feed.sendInteractions call.
type FeedSendInteractions_Input struct {
	Interactions []*FeedDefs_Interaction `json:"interactions" cborgen:"interactions"`
}

// FeedSendInteractions_Output is the output of a app.bsky.feed.sendInteractions call.
type FeedSendInteractions_Output struct {
}

// FeedSendInteractions calls the XRPC method "app.bsky.feed.sendInteractions".
func FeedSendInteractions(ctx context.Context, c lexutil.LexClient, input *FeedSendInteractions_Input) (*FeedSendInteractions_Output, error) {
	var out FeedSendInteractions_Output
	if err := c.LexDo(ctx, lexutil.Procedure, "application/json", "app.bsky.feed.sendInteractions", nil, input, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
