// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: app.bsky.feed.getQuotes

package bsky

import (
	"context"

	lexutil "github.com/bluesky-social/indigo/lex/util"
)

// FeedGetQuotes_Output is the output of a app.bsky.feed.getQuotes call.
type FeedGetQuotes_Output struct {
	Cid    *string              `json:"cid,omitempty" cborgen:"cid,omitempty"`
	Cursor *string              `json:"cursor,omitempty" cborgen:"cursor,omitempty"`
	Posts  []*FeedDefs_PostView `json:"posts" cborgen:"posts"`
	Uri    string               `json:"uri" cborgen:"uri"`
}

// FeedGetQuotes calls the XRPC method "app.bsky.feed.getQuotes".
//
// cid: If supplied, filters to quotes of specific version (by CID) of the post record.
// uri: Reference (AT-URI) of post record
func FeedGetQuotes(ctx context.Context, c lexutil.LexClient, cid string, cursor string, limit int64, uri string) (*FeedGetQuotes_Output, error) {
	var out FeedGetQuotes_Output

	params := map[string]interface{}{}
	if cid != "" {
		params["cid"] = cid
	}
	if cursor != "" {
		params["cursor"] = cursor
	}
	if limit != 0 {
		params["limit"] = limit
	}
	params["uri"] = uri
	if err := c.LexDo(ctx, lexutil.Query, "", "app.bsky.feed.getQuotes", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
