// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package bsky

// schema: app.bsky.feed.postgate

import (
	"github.com/bluesky-social/indigo/lex/util"
)

func init() {
	util.RegisterType("app.bsky.feed.postgate", &FeedPostgate{})
} //
// RECORDTYPE: FeedPostgate
type FeedPostgate struct {
	LexiconTypeID string `json:"$type,const=app.bsky.feed.postgate" cborgen:"$type,const=app.bsky.feed.postgate"`
	CreatedAt     string `json:"createdAt" cborgen:"createdAt"`
	// detachedQuotes: List of detached quote post URIs.
	DetachedQuotes []string `json:"detachedQuotes,omitempty" cborgen:"detachedQuotes,omitempty"`
	// post: Reference (AT-URI) to the post record.
	Post string `json:"post" cborgen:"post"`
}
