// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package bsky

// schema: app.bsky.feed.getFeedGenerators

import (
	"context"

	"github.com/bluesky-social/indigo/xrpc"
)

// FeedGetFeedGenerators_Output is the output of a app.bsky.feed.getFeedGenerators call.
type FeedGetFeedGenerators_Output struct {
	Feeds []*FeedDefs_GeneratorView `json:"feeds" cborgen:"feeds"`
}

// FeedGetFeedGenerators calls the XRPC method "app.bsky.feed.getFeedGenerators".
func FeedGetFeedGenerators(ctx context.Context, c *xrpc.Client, feeds []string) (*FeedGetFeedGenerators_Output, error) {
	var out FeedGetFeedGenerators_Output

	params := map[string]interface{}{
		"feeds": feeds,
	}
	if err := c.Do(ctx, xrpc.Query, "", "app.bsky.feed.getFeedGenerators", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
