// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: app.bsky.graph.getListMutes

package bsky

import (
	"context"

	lexutil "github.com/bluesky-social/indigo/lex/util"
)

// GraphGetListMutes_Output is the output of a app.bsky.graph.getListMutes call.
type GraphGetListMutes_Output struct {
	Cursor *string               `json:"cursor,omitempty" cborgen:"cursor,omitempty"`
	Lists  []*GraphDefs_ListView `json:"lists" cborgen:"lists"`
}

// GraphGetListMutes calls the XRPC method "app.bsky.graph.getListMutes".
func GraphGetListMutes(ctx context.Context, c lexutil.LexClient, cursor string, limit int64) (*GraphGetListMutes_Output, error) {
	var out GraphGetListMutes_Output

	params := map[string]interface{}{}
	if cursor != "" {
		params["cursor"] = cursor
	}
	if limit != 0 {
		params["limit"] = limit
	}
	if err := c.LexDo(ctx, lexutil.Query, "", "app.bsky.graph.getListMutes", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
