// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: app.bsky.graph.muteThread

package bsky

import (
	"context"

	lexutil "github.com/bluesky-social/indigo/lex/util"
)

// GraphMuteThread_Input is the input argument to a app.bsky.graph.muteThread call.
type GraphMuteThread_Input struct {
	Root string `json:"root" cborgen:"root"`
}

// GraphMuteThread calls the XRPC method "app.bsky.graph.muteThread".
func GraphMuteThread(ctx context.Context, c lexutil.LexClient, input *GraphMuteThread_Input) error {
	if err := c.LexDo(ctx, lexutil.Procedure, "application/json", "app.bsky.graph.muteThread", nil, input, nil); err != nil {
		return err
	}

	return nil
}
