// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package bsky

// schema: app.bsky.graph.getActorStarterPacks

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

// GraphGetActorStarterPacks_Output is the output of a app.bsky.graph.getActorStarterPacks call.
type GraphGetActorStarterPacks_Output struct {
	Cursor       *string                           `json:"cursor,omitempty" cborgen:"cursor,omitempty"`
	StarterPacks []*GraphDefs_StarterPackViewBasic `json:"starterPacks" cborgen:"starterPacks"`
}

// GraphGetActorStarterPacks calls the XRPC method "app.bsky.graph.getActorStarterPacks".
func GraphGetActorStarterPacks(ctx context.Context, c util.LexClient, actor string, cursor string, limit int64) (*GraphGetActorStarterPacks_Output, error) {
	var out GraphGetActorStarterPacks_Output

	params := map[string]interface{}{}
	params["actor"] = actor
	if cursor != "" {
		params["cursor"] = cursor
	}
	if limit != 0 {
		params["limit"] = limit
	}
	if err := c.LexDo(ctx, util.Query, "", "app.bsky.graph.getActorStarterPacks", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
