// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package bsky

// schema: app.bsky.graph.searchStarterPacks

import (
	"context"

	"github.com/bluesky-social/indigo/xrpc"
)

// GraphSearchStarterPacks_Output is the output of a app.bsky.graph.searchStarterPacks call.
type GraphSearchStarterPacks_Output struct {
	Cursor       *string                           `json:"cursor,omitempty" cborgen:"cursor,omitempty"`
	StarterPacks []*GraphDefs_StarterPackViewBasic `json:"starterPacks" cborgen:"starterPacks"`
}

// GraphSearchStarterPacks calls the XRPC method "app.bsky.graph.searchStarterPacks".
//
// q: Search query string. Syntax, phrase, boolean, and faceting is unspecified, but Lucene query syntax is recommended.
func GraphSearchStarterPacks(ctx context.Context, c *xrpc.Client, cursor string, limit int64, q string) (*GraphSearchStarterPacks_Output, error) {
	var out GraphSearchStarterPacks_Output

	params := map[string]interface{}{
		"cursor": cursor,
		"limit":  limit,
		"q":      q,
	}
	if err := c.Do(ctx, xrpc.Query, "", "app.bsky.graph.searchStarterPacks", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
