// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package bsky

// schema: app.bsky.graph.unmuteThread

import (
	"context"

	"github.com/bluesky-social/indigo/xrpc"
)

// GraphUnmuteThread_Input is the input argument to a app.bsky.graph.unmuteThread call.
type GraphUnmuteThread_Input struct {
	Root string `json:"root" cborgen:"root"`
}

// GraphUnmuteThread calls the XRPC method "app.bsky.graph.unmuteThread".
func GraphUnmuteThread(ctx context.Context, c *xrpc.Client, input *GraphUnmuteThread_Input) error {
	if err := c.Do(ctx, xrpc.Procedure, "application/json", "app.bsky.graph.unmuteThread", nil, input, nil); err != nil {
		return err
	}

	return nil
}
