// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: app.bsky.graph.listitem

package bsky

import (
	lexutil "github.com/bluesky-social/indigo/lex/util"
)

func init() {
	lexutil.RegisterType("app.bsky.graph.listitem", &GraphListitem{})
}

type GraphListitem struct {
	LexiconTypeID string `json:"$type" cborgen:"$type,const=app.bsky.graph.listitem"`
	CreatedAt     string `json:"createdAt" cborgen:"createdAt"`
	// list: Reference (AT-URI) to the list record (app.bsky.graph.list).
	List string `json:"list" cborgen:"list"`
	// subject: The account which is included on the list.
	Subject string `json:"subject" cborgen:"subject"`
}
