// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: app.bsky.graph.getStarterPacks

package bsky

import (
	"context"

	lexutil "github.com/bluesky-social/indigo/lex/util"
)

// GraphGetStarterPacks_Output is the output of a app.bsky.graph.getStarterPacks call.
type GraphGetStarterPacks_Output struct {
	StarterPacks []*GraphDefs_StarterPackViewBasic `json:"starterPacks" cborgen:"starterPacks"`
}

// GraphGetStarterPacks calls the XRPC method "app.bsky.graph.getStarterPacks".
func GraphGetStarterPacks(ctx context.Context, c lexutil.LexClient, uris []string) (*GraphGetStarterPacks_Output, error) {
	var out GraphGetStarterPacks_Output

	params := map[string]interface{}{}
	params["uris"] = uris
	if err := c.LexDo(ctx, lexutil.Query, "", "app.bsky.graph.getStarterPacks", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
