// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: app.bsky.graph.listblock

package bsky

import (
	lexutil "github.com/bluesky-social/indigo/lex/util"
)

func init() {
	lexutil.RegisterType("app.bsky.graph.listblock", &GraphListblock{})
}

type GraphListblock struct {
	LexiconTypeID string `json:"$type" cborgen:"$type,const=app.bsky.graph.listblock"`
	CreatedAt     string `json:"createdAt" cborgen:"createdAt"`
	// subject: Reference (AT-URI) to the mod list record.
	Subject string `json:"subject" cborgen:"subject"`
}
