// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: app.bsky.graph.follow

package bsky

import (
	comatproto "github.com/bluesky-social/indigo/api/atproto"
	lexutil "github.com/bluesky-social/indigo/lex/util"
)

func init() {
	lexutil.RegisterType("app.bsky.graph.follow", &GraphFollow{})
}

type GraphFollow struct {
	LexiconTypeID string                    `json:"$type" cborgen:"$type,const=app.bsky.graph.follow"`
	CreatedAt     string                    `json:"createdAt" cborgen:"createdAt"`
	Subject       string                    `json:"subject" cborgen:"subject"`
	Via           *comatproto.RepoStrongRef `json:"via,omitempty" cborgen:"via,omitempty"`
}
