// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: app.bsky.notification.listActivitySubscriptions

package bsky

import (
	"context"

	lexutil "github.com/bluesky-social/indigo/lex/util"
)

// NotificationListActivitySubscriptions_Output is the output of a app.bsky.notification.listActivitySubscriptions call.
type NotificationListActivitySubscriptions_Output struct {
	Cursor        *string                  `json:"cursor,omitempty" cborgen:"cursor,omitempty"`
	Subscriptions []*ActorDefs_ProfileView `json:"subscriptions" cborgen:"subscriptions"`
}

// NotificationListActivitySubscriptions calls the XRPC method "app.bsky.notification.listActivitySubscriptions".
func NotificationListActivitySubscriptions(ctx context.Context, c lexutil.LexClient, cursor string, limit int64) (*NotificationListActivitySubscriptions_Output, error) {
	var out NotificationListActivitySubscriptions_Output

	params := map[string]interface{}{}
	if cursor != "" {
		params["cursor"] = cursor
	}
	if limit != 0 {
		params["limit"] = limit
	}
	if err := c.LexDo(ctx, lexutil.Query, "", "app.bsky.notification.listActivitySubscriptions", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
