// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package bsky

// schema: app.bsky.notification.defs

// NotificationDefs_RecordDeleted is a "recordDeleted" in the app.bsky.notification.defs schema.
type NotificationDefs_RecordDeleted struct {
}
