// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package bsky

// schema: app.bsky.notification.getPreferences

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

// NotificationGetPreferences_Output is the output of a app.bsky.notification.getPreferences call.
type NotificationGetPreferences_Output struct {
	Preferences *NotificationDefs_Preferences `json:"preferences" cborgen:"preferences"`
}

// NotificationGetPreferences calls the XRPC method "app.bsky.notification.getPreferences".
func NotificationGetPreferences(ctx context.Context, c util.LexClient) (*NotificationGetPreferences_Output, error) {
	var out NotificationGetPreferences_Output

	params := map[string]interface{}{}
	if err := c.LexDo(ctx, util.Query, "", "app.bsky.notification.getPreferences", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
