// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: app.bsky.notification.getGroupedNotifications

package bsky

import (
	"context"
	"encoding/json"
	"fmt"

	lexutil "github.com/bluesky-social/indigo/lex/util"
)

// NotificationGetGroupedNotifications_ContactMatchNotification is a "contactMatchNotification" in the app.bsky.notification.getGroupedNotifications schema.
//
// A contact of the requesting account joined Bluesky.
type NotificationGetGroupedNotifications_ContactMatchNotification struct {
	LexiconTypeID string `json:"$type" cborgen:"$type,const=app.bsky.notification.getGroupedNotifications#contactMatchNotification"`
	Actor         string `json:"actor" cborgen:"actor"`
}

// NotificationGetGroupedNotifications_FollowBackNotification is a "followBackNotification" in the app.bsky.notification.getGroupedNotifications schema.
//
// An actor followed the requesting account back, possibly via a starter pack.
type NotificationGetGroupedNotifications_FollowBackNotification struct {
	LexiconTypeID string  `json:"$type" cborgen:"$type,const=app.bsky.notification.getGroupedNotifications#followBackNotification"`
	Actor         string  `json:"actor" cborgen:"actor"`
	StarterPack   *string `json:"starterPack,omitempty" cborgen:"starterPack,omitempty"`
}

// NotificationGetGroupedNotifications_FollowGroup is a "followGroup" in the app.bsky.notification.getGroupedNotifications schema.
//
// Group of actors who followed the requesting account.
type NotificationGetGroupedNotifications_FollowGroup struct {
	LexiconTypeID string                                            `json:"$type" cborgen:"$type,const=app.bsky.notification.getGroupedNotifications#followGroup"`
	Items         []*NotificationGetGroupedNotifications_FollowItem `json:"items" cborgen:"items"`
}

// NotificationGetGroupedNotifications_FollowItem is a "followItem" in the app.bsky.notification.getGroupedNotifications schema.
//
// An actor who followed the requesting account, possibly via a starter pack.
type NotificationGetGroupedNotifications_FollowItem struct {
	Actor       string  `json:"actor" cborgen:"actor"`
	StarterPack *string `json:"starterPack,omitempty" cborgen:"starterPack,omitempty"`
}

// NotificationGetGroupedNotifications_GeneratorLikeGroup is a "generatorLikeGroup" in the app.bsky.notification.getGroupedNotifications schema.
//
// Group of likes by different actors on the same feed generator.
type NotificationGetGroupedNotifications_GeneratorLikeGroup struct {
	LexiconTypeID string                                                   `json:"$type" cborgen:"$type,const=app.bsky.notification.getGroupedNotifications#generatorLikeGroup"`
	Generator     string                                                   `json:"generator" cborgen:"generator"`
	Items         []*NotificationGetGroupedNotifications_GeneratorLikeItem `json:"items" cborgen:"items"`
}

// NotificationGetGroupedNotifications_GeneratorLikeItem is a "generatorLikeItem" in the app.bsky.notification.getGroupedNotifications schema.
//
// One actor who liked the feed generator in the group.
type NotificationGetGroupedNotifications_GeneratorLikeItem struct {
	Actor string `json:"actor" cborgen:"actor"`
}

// NotificationGetGroupedNotifications_Group is a "group" in the app.bsky.notification.getGroupedNotifications schema.
//
// Contains common metadata and kind-specific data for a notification group or individual notification.
type NotificationGetGroupedNotifications_Group struct {
	Count     int64                                           `json:"count" cborgen:"count"`
	Id        string                                          `json:"id" cborgen:"id"`
	IndexedAt string                                          `json:"indexedAt" cborgen:"indexedAt"`
	IsRead    bool                                            `json:"isRead" cborgen:"isRead"`
	Kind      *NotificationGetGroupedNotifications_Group_Kind `json:"kind" cborgen:"kind"`
}

type NotificationGetGroupedNotifications_Group_Kind struct {
	NotificationGetGroupedNotifications_LikeGroup                     *NotificationGetGroupedNotifications_LikeGroup
	NotificationGetGroupedNotifications_MultiPostLikeGroup            *NotificationGetGroupedNotifications_MultiPostLikeGroup
	NotificationGetGroupedNotifications_RepostGroup                   *NotificationGetGroupedNotifications_RepostGroup
	NotificationGetGroupedNotifications_LikeViaRepostGroup            *NotificationGetGroupedNotifications_LikeViaRepostGroup
	NotificationGetGroupedNotifications_RepostViaRepostGroup          *NotificationGetGroupedNotifications_RepostViaRepostGroup
	NotificationGetGroupedNotifications_FollowGroup                   *NotificationGetGroupedNotifications_FollowGroup
	NotificationGetGroupedNotifications_SubscribedPostGroup           *NotificationGetGroupedNotifications_SubscribedPostGroup
	NotificationGetGroupedNotifications_GeneratorLikeGroup            *NotificationGetGroupedNotifications_GeneratorLikeGroup
	NotificationGetGroupedNotifications_ReplyNotification             *NotificationGetGroupedNotifications_ReplyNotification
	NotificationGetGroupedNotifications_QuoteNotification             *NotificationGetGroupedNotifications_QuoteNotification
	NotificationGetGroupedNotifications_MentionNotification           *NotificationGetGroupedNotifications_MentionNotification
	NotificationGetGroupedNotifications_FollowBackNotification        *NotificationGetGroupedNotifications_FollowBackNotification
	NotificationGetGroupedNotifications_VerifiedNotification          *NotificationGetGroupedNotifications_VerifiedNotification
	NotificationGetGroupedNotifications_UnverifiedNotification        *NotificationGetGroupedNotifications_UnverifiedNotification
	NotificationGetGroupedNotifications_StarterPackJoinedNotification *NotificationGetGroupedNotifications_StarterPackJoinedNotification
	NotificationGetGroupedNotifications_ContactMatchNotification      *NotificationGetGroupedNotifications_ContactMatchNotification
}

func (t *NotificationGetGroupedNotifications_Group_Kind) MarshalJSON() ([]byte, error) {
	if t.NotificationGetGroupedNotifications_LikeGroup != nil {
		t.NotificationGetGroupedNotifications_LikeGroup.LexiconTypeID = "app.bsky.notification.getGroupedNotifications#likeGroup"
		return json.Marshal(t.NotificationGetGroupedNotifications_LikeGroup)
	}
	if t.NotificationGetGroupedNotifications_MultiPostLikeGroup != nil {
		t.NotificationGetGroupedNotifications_MultiPostLikeGroup.LexiconTypeID = "app.bsky.notification.getGroupedNotifications#multiPostLikeGroup"
		return json.Marshal(t.NotificationGetGroupedNotifications_MultiPostLikeGroup)
	}
	if t.NotificationGetGroupedNotifications_RepostGroup != nil {
		t.NotificationGetGroupedNotifications_RepostGroup.LexiconTypeID = "app.bsky.notification.getGroupedNotifications#repostGroup"
		return json.Marshal(t.NotificationGetGroupedNotifications_RepostGroup)
	}
	if t.NotificationGetGroupedNotifications_LikeViaRepostGroup != nil {
		t.NotificationGetGroupedNotifications_LikeViaRepostGroup.LexiconTypeID = "app.bsky.notification.getGroupedNotifications#likeViaRepostGroup"
		return json.Marshal(t.NotificationGetGroupedNotifications_LikeViaRepostGroup)
	}
	if t.NotificationGetGroupedNotifications_RepostViaRepostGroup != nil {
		t.NotificationGetGroupedNotifications_RepostViaRepostGroup.LexiconTypeID = "app.bsky.notification.getGroupedNotifications#repostViaRepostGroup"
		return json.Marshal(t.NotificationGetGroupedNotifications_RepostViaRepostGroup)
	}
	if t.NotificationGetGroupedNotifications_FollowGroup != nil {
		t.NotificationGetGroupedNotifications_FollowGroup.LexiconTypeID = "app.bsky.notification.getGroupedNotifications#followGroup"
		return json.Marshal(t.NotificationGetGroupedNotifications_FollowGroup)
	}
	if t.NotificationGetGroupedNotifications_SubscribedPostGroup != nil {
		t.NotificationGetGroupedNotifications_SubscribedPostGroup.LexiconTypeID = "app.bsky.notification.getGroupedNotifications#subscribedPostGroup"
		return json.Marshal(t.NotificationGetGroupedNotifications_SubscribedPostGroup)
	}
	if t.NotificationGetGroupedNotifications_GeneratorLikeGroup != nil {
		t.NotificationGetGroupedNotifications_GeneratorLikeGroup.LexiconTypeID = "app.bsky.notification.getGroupedNotifications#generatorLikeGroup"
		return json.Marshal(t.NotificationGetGroupedNotifications_GeneratorLikeGroup)
	}
	if t.NotificationGetGroupedNotifications_ReplyNotification != nil {
		t.NotificationGetGroupedNotifications_ReplyNotification.LexiconTypeID = "app.bsky.notification.getGroupedNotifications#replyNotification"
		return json.Marshal(t.NotificationGetGroupedNotifications_ReplyNotification)
	}
	if t.NotificationGetGroupedNotifications_QuoteNotification != nil {
		t.NotificationGetGroupedNotifications_QuoteNotification.LexiconTypeID = "app.bsky.notification.getGroupedNotifications#quoteNotification"
		return json.Marshal(t.NotificationGetGroupedNotifications_QuoteNotification)
	}
	if t.NotificationGetGroupedNotifications_MentionNotification != nil {
		t.NotificationGetGroupedNotifications_MentionNotification.LexiconTypeID = "app.bsky.notification.getGroupedNotifications#mentionNotification"
		return json.Marshal(t.NotificationGetGroupedNotifications_MentionNotification)
	}
	if t.NotificationGetGroupedNotifications_FollowBackNotification != nil {
		t.NotificationGetGroupedNotifications_FollowBackNotification.LexiconTypeID = "app.bsky.notification.getGroupedNotifications#followBackNotification"
		return json.Marshal(t.NotificationGetGroupedNotifications_FollowBackNotification)
	}
	if t.NotificationGetGroupedNotifications_VerifiedNotification != nil {
		t.NotificationGetGroupedNotifications_VerifiedNotification.LexiconTypeID = "app.bsky.notification.getGroupedNotifications#verifiedNotification"
		return json.Marshal(t.NotificationGetGroupedNotifications_VerifiedNotification)
	}
	if t.NotificationGetGroupedNotifications_UnverifiedNotification != nil {
		t.NotificationGetGroupedNotifications_UnverifiedNotification.LexiconTypeID = "app.bsky.notification.getGroupedNotifications#unverifiedNotification"
		return json.Marshal(t.NotificationGetGroupedNotifications_UnverifiedNotification)
	}
	if t.NotificationGetGroupedNotifications_StarterPackJoinedNotification != nil {
		t.NotificationGetGroupedNotifications_StarterPackJoinedNotification.LexiconTypeID = "app.bsky.notification.getGroupedNotifications#starterPackJoinedNotification"
		return json.Marshal(t.NotificationGetGroupedNotifications_StarterPackJoinedNotification)
	}
	if t.NotificationGetGroupedNotifications_ContactMatchNotification != nil {
		t.NotificationGetGroupedNotifications_ContactMatchNotification.LexiconTypeID = "app.bsky.notification.getGroupedNotifications#contactMatchNotification"
		return json.Marshal(t.NotificationGetGroupedNotifications_ContactMatchNotification)
	}
	return nil, fmt.Errorf("can not marshal empty union as JSON")
}

func (t *NotificationGetGroupedNotifications_Group_Kind) UnmarshalJSON(b []byte) error {
	typ, err := lexutil.TypeExtract(b)
	if err != nil {
		return err
	}

	switch typ {
	case "app.bsky.notification.getGroupedNotifications#likeGroup":
		t.NotificationGetGroupedNotifications_LikeGroup = new(NotificationGetGroupedNotifications_LikeGroup)
		return json.Unmarshal(b, t.NotificationGetGroupedNotifications_LikeGroup)
	case "app.bsky.notification.getGroupedNotifications#multiPostLikeGroup":
		t.NotificationGetGroupedNotifications_MultiPostLikeGroup = new(NotificationGetGroupedNotifications_MultiPostLikeGroup)
		return json.Unmarshal(b, t.NotificationGetGroupedNotifications_MultiPostLikeGroup)
	case "app.bsky.notification.getGroupedNotifications#repostGroup":
		t.NotificationGetGroupedNotifications_RepostGroup = new(NotificationGetGroupedNotifications_RepostGroup)
		return json.Unmarshal(b, t.NotificationGetGroupedNotifications_RepostGroup)
	case "app.bsky.notification.getGroupedNotifications#likeViaRepostGroup":
		t.NotificationGetGroupedNotifications_LikeViaRepostGroup = new(NotificationGetGroupedNotifications_LikeViaRepostGroup)
		return json.Unmarshal(b, t.NotificationGetGroupedNotifications_LikeViaRepostGroup)
	case "app.bsky.notification.getGroupedNotifications#repostViaRepostGroup":
		t.NotificationGetGroupedNotifications_RepostViaRepostGroup = new(NotificationGetGroupedNotifications_RepostViaRepostGroup)
		return json.Unmarshal(b, t.NotificationGetGroupedNotifications_RepostViaRepostGroup)
	case "app.bsky.notification.getGroupedNotifications#followGroup":
		t.NotificationGetGroupedNotifications_FollowGroup = new(NotificationGetGroupedNotifications_FollowGroup)
		return json.Unmarshal(b, t.NotificationGetGroupedNotifications_FollowGroup)
	case "app.bsky.notification.getGroupedNotifications#subscribedPostGroup":
		t.NotificationGetGroupedNotifications_SubscribedPostGroup = new(NotificationGetGroupedNotifications_SubscribedPostGroup)
		return json.Unmarshal(b, t.NotificationGetGroupedNotifications_SubscribedPostGroup)
	case "app.bsky.notification.getGroupedNotifications#generatorLikeGroup":
		t.NotificationGetGroupedNotifications_GeneratorLikeGroup = new(NotificationGetGroupedNotifications_GeneratorLikeGroup)
		return json.Unmarshal(b, t.NotificationGetGroupedNotifications_GeneratorLikeGroup)
	case "app.bsky.notification.getGroupedNotifications#replyNotification":
		t.NotificationGetGroupedNotifications_ReplyNotification = new(NotificationGetGroupedNotifications_ReplyNotification)
		return json.Unmarshal(b, t.NotificationGetGroupedNotifications_ReplyNotification)
	case "app.bsky.notification.getGroupedNotifications#quoteNotification":
		t.NotificationGetGroupedNotifications_QuoteNotification = new(NotificationGetGroupedNotifications_QuoteNotification)
		return json.Unmarshal(b, t.NotificationGetGroupedNotifications_QuoteNotification)
	case "app.bsky.notification.getGroupedNotifications#mentionNotification":
		t.NotificationGetGroupedNotifications_MentionNotification = new(NotificationGetGroupedNotifications_MentionNotification)
		return json.Unmarshal(b, t.NotificationGetGroupedNotifications_MentionNotification)
	case "app.bsky.notification.getGroupedNotifications#followBackNotification":
		t.NotificationGetGroupedNotifications_FollowBackNotification = new(NotificationGetGroupedNotifications_FollowBackNotification)
		return json.Unmarshal(b, t.NotificationGetGroupedNotifications_FollowBackNotification)
	case "app.bsky.notification.getGroupedNotifications#verifiedNotification":
		t.NotificationGetGroupedNotifications_VerifiedNotification = new(NotificationGetGroupedNotifications_VerifiedNotification)
		return json.Unmarshal(b, t.NotificationGetGroupedNotifications_VerifiedNotification)
	case "app.bsky.notification.getGroupedNotifications#unverifiedNotification":
		t.NotificationGetGroupedNotifications_UnverifiedNotification = new(NotificationGetGroupedNotifications_UnverifiedNotification)
		return json.Unmarshal(b, t.NotificationGetGroupedNotifications_UnverifiedNotification)
	case "app.bsky.notification.getGroupedNotifications#starterPackJoinedNotification":
		t.NotificationGetGroupedNotifications_StarterPackJoinedNotification = new(NotificationGetGroupedNotifications_StarterPackJoinedNotification)
		return json.Unmarshal(b, t.NotificationGetGroupedNotifications_StarterPackJoinedNotification)
	case "app.bsky.notification.getGroupedNotifications#contactMatchNotification":
		t.NotificationGetGroupedNotifications_ContactMatchNotification = new(NotificationGetGroupedNotifications_ContactMatchNotification)
		return json.Unmarshal(b, t.NotificationGetGroupedNotifications_ContactMatchNotification)
	default:
		return nil
	}
}

// NotificationGetGroupedNotifications_LikeGroup is a "likeGroup" in the app.bsky.notification.getGroupedNotifications schema.
//
// Group of likes by different actors on the same post.
type NotificationGetGroupedNotifications_LikeGroup struct {
	LexiconTypeID string                                          `json:"$type" cborgen:"$type,const=app.bsky.notification.getGroupedNotifications#likeGroup"`
	Items         []*NotificationGetGroupedNotifications_LikeItem `json:"items" cborgen:"items"`
	Post          string                                          `json:"post" cborgen:"post"`
}

// NotificationGetGroupedNotifications_LikeItem is a "likeItem" in the app.bsky.notification.getGroupedNotifications schema.
//
// One actor who liked the group's post.
type NotificationGetGroupedNotifications_LikeItem struct {
	Actor string `json:"actor" cborgen:"actor"`
}

// NotificationGetGroupedNotifications_LikeViaRepostGroup is a "likeViaRepostGroup" in the app.bsky.notification.getGroupedNotifications schema.
//
// Group of likes by different actors on the same post via the requesting account's repost.
type NotificationGetGroupedNotifications_LikeViaRepostGroup struct {
	LexiconTypeID string                                                   `json:"$type" cborgen:"$type,const=app.bsky.notification.getGroupedNotifications#likeViaRepostGroup"`
	Items         []*NotificationGetGroupedNotifications_LikeViaRepostItem `json:"items" cborgen:"items"`
	Post          string                                                   `json:"post" cborgen:"post"`
	ViaRepost     string                                                   `json:"viaRepost" cborgen:"viaRepost"`
}

// NotificationGetGroupedNotifications_LikeViaRepostItem is a "likeViaRepostItem" in the app.bsky.notification.getGroupedNotifications schema.
//
// One actor who liked the group's post via the requesting account's repost.
type NotificationGetGroupedNotifications_LikeViaRepostItem struct {
	Actor string `json:"actor" cborgen:"actor"`
}

// NotificationGetGroupedNotifications_MentionNotification is a "mentionNotification" in the app.bsky.notification.getGroupedNotifications schema.
//
// A post mentioning the requesting account.
type NotificationGetGroupedNotifications_MentionNotification struct {
	LexiconTypeID string  `json:"$type" cborgen:"$type,const=app.bsky.notification.getGroupedNotifications#mentionNotification"`
	Parent        *string `json:"parent,omitempty" cborgen:"parent,omitempty"`
	Post          string  `json:"post" cborgen:"post"`
}

// NotificationGetGroupedNotifications_MultiPostLikeGroup is a "multiPostLikeGroup" in the app.bsky.notification.getGroupedNotifications schema.
//
// Group of likes by the same actor on different posts.
type NotificationGetGroupedNotifications_MultiPostLikeGroup struct {
	LexiconTypeID string                                                   `json:"$type" cborgen:"$type,const=app.bsky.notification.getGroupedNotifications#multiPostLikeGroup"`
	Actor         string                                                   `json:"actor" cborgen:"actor"`
	Items         []*NotificationGetGroupedNotifications_MultiPostLikeItem `json:"items" cborgen:"items"`
}

// NotificationGetGroupedNotifications_MultiPostLikeItem is a "multiPostLikeItem" in the app.bsky.notification.getGroupedNotifications schema.
//
// One post which was liked by the group's actor.
type NotificationGetGroupedNotifications_MultiPostLikeItem struct {
	Post string `json:"post" cborgen:"post"`
}

// NotificationGetGroupedNotifications_Output is the output of a app.bsky.notification.getGroupedNotifications call.
type NotificationGetGroupedNotifications_Output struct {
	Cursor *string `json:"cursor,omitempty" cborgen:"cursor,omitempty"`
	// groups: Notification groups or individual notifications, newest first. Clients should ignore kinds they do not recognize. Grouping behavior depends on the kind and selected feed.
	Groups []*NotificationGetGroupedNotifications_Group `json:"groups" cborgen:"groups"`
	// relatedViews: Reusable views referenced by notifications. Views shared across notifications appear once to avoid duplication. Each group contributes only its first 10 of each related view to this array. Ex: for a group containing likes in a post, we might have a large number of likeItem (e.g., 50) in a group, but only the profile views for the newest 10 items will be included here.
	RelatedViews []*NotificationGetGroupedNotifications_Output_RelatedViews_Elem `json:"relatedViews,omitempty" cborgen:"relatedViews,omitempty"`
	SeenAt       *string                                                         `json:"seenAt,omitempty" cborgen:"seenAt,omitempty"`
}

type NotificationGetGroupedNotifications_Output_RelatedViews_Elem struct {
	ActorDefs_ProfileViewDetailed *ActorDefs_ProfileViewDetailed
	FeedDefs_BlockedPost          *FeedDefs_BlockedPost
	FeedDefs_GeneratorView        *FeedDefs_GeneratorView
	FeedDefs_NotFoundPost         *FeedDefs_NotFoundPost
	FeedDefs_PostView             *FeedDefs_PostView
	GraphDefs_StarterPackView     *GraphDefs_StarterPackView
}

func (t *NotificationGetGroupedNotifications_Output_RelatedViews_Elem) MarshalJSON() ([]byte, error) {
	if t.ActorDefs_ProfileViewDetailed != nil {
		t.ActorDefs_ProfileViewDetailed.LexiconTypeID = "app.bsky.actor.defs#profileViewDetailed"
		return json.Marshal(t.ActorDefs_ProfileViewDetailed)
	}
	if t.FeedDefs_BlockedPost != nil {
		t.FeedDefs_BlockedPost.LexiconTypeID = "app.bsky.feed.defs#blockedPost"
		return json.Marshal(t.FeedDefs_BlockedPost)
	}
	if t.FeedDefs_GeneratorView != nil {
		t.FeedDefs_GeneratorView.LexiconTypeID = "app.bsky.feed.defs#generatorView"
		return json.Marshal(t.FeedDefs_GeneratorView)
	}
	if t.FeedDefs_NotFoundPost != nil {
		t.FeedDefs_NotFoundPost.LexiconTypeID = "app.bsky.feed.defs#notFoundPost"
		return json.Marshal(t.FeedDefs_NotFoundPost)
	}
	if t.FeedDefs_PostView != nil {
		t.FeedDefs_PostView.LexiconTypeID = "app.bsky.feed.defs#postView"
		return json.Marshal(t.FeedDefs_PostView)
	}
	if t.GraphDefs_StarterPackView != nil {
		t.GraphDefs_StarterPackView.LexiconTypeID = "app.bsky.graph.defs#starterPackView"
		return json.Marshal(t.GraphDefs_StarterPackView)
	}
	return nil, fmt.Errorf("can not marshal empty union as JSON")
}

func (t *NotificationGetGroupedNotifications_Output_RelatedViews_Elem) UnmarshalJSON(b []byte) error {
	typ, err := lexutil.TypeExtract(b)
	if err != nil {
		return err
	}

	switch typ {
	case "app.bsky.actor.defs#profileViewDetailed":
		t.ActorDefs_ProfileViewDetailed = new(ActorDefs_ProfileViewDetailed)
		return json.Unmarshal(b, t.ActorDefs_ProfileViewDetailed)
	case "app.bsky.feed.defs#blockedPost":
		t.FeedDefs_BlockedPost = new(FeedDefs_BlockedPost)
		return json.Unmarshal(b, t.FeedDefs_BlockedPost)
	case "app.bsky.feed.defs#generatorView":
		t.FeedDefs_GeneratorView = new(FeedDefs_GeneratorView)
		return json.Unmarshal(b, t.FeedDefs_GeneratorView)
	case "app.bsky.feed.defs#notFoundPost":
		t.FeedDefs_NotFoundPost = new(FeedDefs_NotFoundPost)
		return json.Unmarshal(b, t.FeedDefs_NotFoundPost)
	case "app.bsky.feed.defs#postView":
		t.FeedDefs_PostView = new(FeedDefs_PostView)
		return json.Unmarshal(b, t.FeedDefs_PostView)
	case "app.bsky.graph.defs#starterPackView":
		t.GraphDefs_StarterPackView = new(GraphDefs_StarterPackView)
		return json.Unmarshal(b, t.GraphDefs_StarterPackView)
	default:
		return nil
	}
}

// NotificationGetGroupedNotifications_QuoteNotification is a "quoteNotification" in the app.bsky.notification.getGroupedNotifications schema.
//
// A post quoting a post by the requesting account.
type NotificationGetGroupedNotifications_QuoteNotification struct {
	LexiconTypeID string  `json:"$type" cborgen:"$type,const=app.bsky.notification.getGroupedNotifications#quoteNotification"`
	Parent        *string `json:"parent,omitempty" cborgen:"parent,omitempty"`
	Post          string  `json:"post" cborgen:"post"`
}

// NotificationGetGroupedNotifications_ReplyNotification is a "replyNotification" in the app.bsky.notification.getGroupedNotifications schema.
//
// A reply to a post by the requesting account or to a thread they are participating in.
type NotificationGetGroupedNotifications_ReplyNotification struct {
	LexiconTypeID string `json:"$type" cborgen:"$type,const=app.bsky.notification.getGroupedNotifications#replyNotification"`
	Parent        string `json:"parent" cborgen:"parent"`
	Post          string `json:"post" cborgen:"post"`
}

// NotificationGetGroupedNotifications_RepostGroup is a "repostGroup" in the app.bsky.notification.getGroupedNotifications schema.
//
// Group of reposts by different actors of the same post.
type NotificationGetGroupedNotifications_RepostGroup struct {
	LexiconTypeID string                                            `json:"$type" cborgen:"$type,const=app.bsky.notification.getGroupedNotifications#repostGroup"`
	Items         []*NotificationGetGroupedNotifications_RepostItem `json:"items" cborgen:"items"`
	Post          string                                            `json:"post" cborgen:"post"`
}

// NotificationGetGroupedNotifications_RepostItem is a "repostItem" in the app.bsky.notification.getGroupedNotifications schema.
//
// One actor who reposted the group's post.
type NotificationGetGroupedNotifications_RepostItem struct {
	Actor string `json:"actor" cborgen:"actor"`
}

// NotificationGetGroupedNotifications_RepostViaRepostGroup is a "repostViaRepostGroup" in the app.bsky.notification.getGroupedNotifications schema.
//
// Group of reposts by different actors of the same post via the requesting account's repost.
type NotificationGetGroupedNotifications_RepostViaRepostGroup struct {
	LexiconTypeID string                                                     `json:"$type" cborgen:"$type,const=app.bsky.notification.getGroupedNotifications#repostViaRepostGroup"`
	Items         []*NotificationGetGroupedNotifications_RepostViaRepostItem `json:"items" cborgen:"items"`
	Post          string                                                     `json:"post" cborgen:"post"`
	ViaRepost     string                                                     `json:"viaRepost" cborgen:"viaRepost"`
}

// NotificationGetGroupedNotifications_RepostViaRepostItem is a "repostViaRepostItem" in the app.bsky.notification.getGroupedNotifications schema.
//
// One actor who reposted the group's post via the requesting account's repost.
type NotificationGetGroupedNotifications_RepostViaRepostItem struct {
	Actor string `json:"actor" cborgen:"actor"`
}

// NotificationGetGroupedNotifications_StarterPackJoinedNotification is a "starterPackJoinedNotification" in the app.bsky.notification.getGroupedNotifications schema.
//
// An actor joined Bluesky via a starter pack created by the requesting account.
type NotificationGetGroupedNotifications_StarterPackJoinedNotification struct {
	LexiconTypeID string `json:"$type" cborgen:"$type,const=app.bsky.notification.getGroupedNotifications#starterPackJoinedNotification"`
	Actor         string `json:"actor" cborgen:"actor"`
	StarterPack   string `json:"starterPack" cborgen:"starterPack"`
}

// NotificationGetGroupedNotifications_SubscribedPostGroup is a "subscribedPostGroup" in the app.bsky.notification.getGroupedNotifications schema.
//
// Group of new posts by actors the requesting account subscribes to.
type NotificationGetGroupedNotifications_SubscribedPostGroup struct {
	LexiconTypeID string                                                    `json:"$type" cborgen:"$type,const=app.bsky.notification.getGroupedNotifications#subscribedPostGroup"`
	Items         []*NotificationGetGroupedNotifications_SubscribedPostItem `json:"items" cborgen:"items"`
}

// NotificationGetGroupedNotifications_SubscribedPostItem is a "subscribedPostItem" in the app.bsky.notification.getGroupedNotifications schema.
//
// One new post by an actor the requesting account subscribes to.
type NotificationGetGroupedNotifications_SubscribedPostItem struct {
	Actor string `json:"actor" cborgen:"actor"`
	Post  string `json:"post" cborgen:"post"`
}

// NotificationGetGroupedNotifications_UnverifiedNotification is a "unverifiedNotification" in the app.bsky.notification.getGroupedNotifications schema.
//
// A verification of the requesting account was removed.
type NotificationGetGroupedNotifications_UnverifiedNotification struct {
	LexiconTypeID string `json:"$type" cborgen:"$type,const=app.bsky.notification.getGroupedNotifications#unverifiedNotification"`
	Actor         string `json:"actor" cborgen:"actor"`
}

// NotificationGetGroupedNotifications_VerifiedNotification is a "verifiedNotification" in the app.bsky.notification.getGroupedNotifications schema.
//
// An actor verified the requesting account.
type NotificationGetGroupedNotifications_VerifiedNotification struct {
	LexiconTypeID string `json:"$type" cborgen:"$type,const=app.bsky.notification.getGroupedNotifications#verifiedNotification"`
	Actor         string `json:"actor" cborgen:"actor"`
}

// NotificationGetGroupedNotifications calls the XRPC method "app.bsky.notification.getGroupedNotifications".
//
// feed: Which notification feed to return. Grouping behavior varies by feed: notifications about follows might be grouped in 'all' and ungrouped (or rather, in single-item groups) in 'followers'.
// limit: Maximum number of groups to return.
func NotificationGetGroupedNotifications(ctx context.Context, c lexutil.LexClient, cursor string, feed string, limit int64) (*NotificationGetGroupedNotifications_Output, error) {
	var out NotificationGetGroupedNotifications_Output

	params := map[string]interface{}{}
	if cursor != "" {
		params["cursor"] = cursor
	}
	if feed != "" {
		params["feed"] = feed
	}
	if limit != 0 {
		params["limit"] = limit
	}
	if err := c.LexDo(ctx, lexutil.Query, "", "app.bsky.notification.getGroupedNotifications", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
