// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: app.bsky.unspecced.getSuggestedUsersForDiscoverSkeleton

package bsky

import (
	"context"

	lexutil "github.com/bluesky-social/indigo/lex/util"
)

// UnspeccedGetSuggestedUsersForDiscoverSkeleton_Output is the output of a app.bsky.unspecced.getSuggestedUsersForDiscoverSkeleton call.
type UnspeccedGetSuggestedUsersForDiscoverSkeleton_Output struct {
	Dids []string `json:"dids" cborgen:"dids"`
	// recIdStr: Snowflake for this recommendation, use when submitting recommendation events.
	RecIdStr *string `json:"recIdStr,omitempty" cborgen:"recIdStr,omitempty"`
}

// UnspeccedGetSuggestedUsersForDiscoverSkeleton calls the XRPC method "app.bsky.unspecced.getSuggestedUsersForDiscoverSkeleton".
//
// viewer: DID of the account making the request (not included for public/unauthenticated queries).
func UnspeccedGetSuggestedUsersForDiscoverSkeleton(ctx context.Context, c lexutil.LexClient, limit int64, viewer string) (*UnspeccedGetSuggestedUsersForDiscoverSkeleton_Output, error) {
	var out UnspeccedGetSuggestedUsersForDiscoverSkeleton_Output

	params := map[string]interface{}{}
	if limit != 0 {
		params["limit"] = limit
	}
	if viewer != "" {
		params["viewer"] = viewer
	}
	if err := c.LexDo(ctx, lexutil.Query, "", "app.bsky.unspecced.getSuggestedUsersForDiscoverSkeleton", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
