// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: app.bsky.unspecced.getTaggedSuggestions

package bsky

import (
	"context"

	lexutil "github.com/bluesky-social/indigo/lex/util"
)

// UnspeccedGetTaggedSuggestions_Output is the output of a app.bsky.unspecced.getTaggedSuggestions call.
type UnspeccedGetTaggedSuggestions_Output struct {
	Suggestions []*UnspeccedGetTaggedSuggestions_Suggestion `json:"suggestions" cborgen:"suggestions"`
}

// UnspeccedGetTaggedSuggestions_Suggestion is a "suggestion" in the app.bsky.unspecced.getTaggedSuggestions schema.
type UnspeccedGetTaggedSuggestions_Suggestion struct {
	Subject     string `json:"subject" cborgen:"subject"`
	SubjectType string `json:"subjectType" cborgen:"subjectType"`
	Tag         string `json:"tag" cborgen:"tag"`
}

// UnspeccedGetTaggedSuggestions calls the XRPC method "app.bsky.unspecced.getTaggedSuggestions".
func UnspeccedGetTaggedSuggestions(ctx context.Context, c lexutil.LexClient) (*UnspeccedGetTaggedSuggestions_Output, error) {
	var out UnspeccedGetTaggedSuggestions_Output

	params := map[string]interface{}{}
	if err := c.LexDo(ctx, lexutil.Query, "", "app.bsky.unspecced.getTaggedSuggestions", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
