// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: app.bsky.unspecced.getSuggestedOnboardingUsers

package bsky

import (
	"context"

	lexutil "github.com/bluesky-social/indigo/lex/util"
)

// UnspeccedGetSuggestedOnboardingUsers_Output is the output of a app.bsky.unspecced.getSuggestedOnboardingUsers call.
type UnspeccedGetSuggestedOnboardingUsers_Output struct {
	Actors []*ActorDefs_ProfileView `json:"actors" cborgen:"actors"`
	// recId: DEPRECATED: use recIdStr instead.
	RecId *string `json:"recId,omitempty" cborgen:"recId,omitempty"`
	// recIdStr: Snowflake for this recommendation, use when submitting recommendation events.
	RecIdStr *string `json:"recIdStr,omitempty" cborgen:"recIdStr,omitempty"`
}

// UnspeccedGetSuggestedOnboardingUsers calls the XRPC method "app.bsky.unspecced.getSuggestedOnboardingUsers".
//
// category: Category of users to get suggestions for.
func UnspeccedGetSuggestedOnboardingUsers(ctx context.Context, c lexutil.LexClient, category string, limit int64) (*UnspeccedGetSuggestedOnboardingUsers_Output, error) {
	var out UnspeccedGetSuggestedOnboardingUsers_Output

	params := map[string]interface{}{}
	if category != "" {
		params["category"] = category
	}
	if limit != 0 {
		params["limit"] = limit
	}
	if err := c.LexDo(ctx, lexutil.Query, "", "app.bsky.unspecced.getSuggestedOnboardingUsers", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
