// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package bsky

// schema: app.bsky.unspecced.getConfig

import (
	"context"

	"github.com/bluesky-social/indigo/xrpc"
)

// UnspeccedGetConfig_Output is the output of a app.bsky.unspecced.getConfig call.
type UnspeccedGetConfig_Output struct {
	CheckEmailConfirmed *bool `json:"checkEmailConfirmed,omitempty" cborgen:"checkEmailConfirmed,omitempty"`
}

// UnspeccedGetConfig calls the XRPC method "app.bsky.unspecced.getConfig".
func UnspeccedGetConfig(ctx context.Context, c *xrpc.Client) (*UnspeccedGetConfig_Output, error) {
	var out UnspeccedGetConfig_Output
	if err := c.Do(ctx, xrpc.Query, "", "app.bsky.unspecced.getConfig", nil, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
