// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: app.bsky.unspecced.getSuggestedUsersSkeleton

package bsky

import (
	"context"

	lexutil "github.com/bluesky-social/indigo/lex/util"
)

// UnspeccedGetSuggestedUsersSkeleton_Output is the output of a app.bsky.unspecced.getSuggestedUsersSkeleton call.
type UnspeccedGetSuggestedUsersSkeleton_Output struct {
	Dids []string `json:"dids" cborgen:"dids"`
	// recId: Snowflake for this recommendation, use when submitting recommendation events.
	RecId *int64 `json:"recId,omitempty" cborgen:"recId,omitempty"`
}

// UnspeccedGetSuggestedUsersSkeleton calls the XRPC method "app.bsky.unspecced.getSuggestedUsersSkeleton".
//
// category: Category of users to get suggestions for.
// viewer: DID of the account making the request (not included for public/unauthenticated queries).
func UnspeccedGetSuggestedUsersSkeleton(ctx context.Context, c lexutil.LexClient, category string, limit int64, viewer string) (*UnspeccedGetSuggestedUsersSkeleton_Output, error) {
	var out UnspeccedGetSuggestedUsersSkeleton_Output

	params := map[string]interface{}{}
	if category != "" {
		params["category"] = category
	}
	if limit != 0 {
		params["limit"] = limit
	}
	if viewer != "" {
		params["viewer"] = viewer
	}
	if err := c.LexDo(ctx, lexutil.Query, "", "app.bsky.unspecced.getSuggestedUsersSkeleton", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
