// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package bsky

// schema: app.bsky.unspecced.getSuggestedFeeds

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

// UnspeccedGetSuggestedFeeds_Output is the output of a app.bsky.unspecced.getSuggestedFeeds call.
type UnspeccedGetSuggestedFeeds_Output struct {
	Feeds []*FeedDefs_GeneratorView `json:"feeds" cborgen:"feeds"`
}

// UnspeccedGetSuggestedFeeds calls the XRPC method "app.bsky.unspecced.getSuggestedFeeds".
func UnspeccedGetSuggestedFeeds(ctx context.Context, c util.LexClient, limit int64) (*UnspeccedGetSuggestedFeeds_Output, error) {
	var out UnspeccedGetSuggestedFeeds_Output

	params := map[string]interface{}{}
	if limit != 0 {
		params["limit"] = limit
	}
	if err := c.LexDo(ctx, util.Query, "", "app.bsky.unspecced.getSuggestedFeeds", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
