// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package bsky

// schema: app.bsky.video.getJobStatus

import (
	"context"

	"github.com/bluesky-social/indigo/xrpc"
)

// VideoGetJobStatus_Output is the output of a app.bsky.video.getJobStatus call.
type VideoGetJobStatus_Output struct {
	JobStatus *VideoDefs_JobStatus `json:"jobStatus" cborgen:"jobStatus"`
}

// VideoGetJobStatus calls the XRPC method "app.bsky.video.getJobStatus".
func VideoGetJobStatus(ctx context.Context, c *xrpc.Client, jobId string) (*VideoGetJobStatus_Output, error) {
	var out VideoGetJobStatus_Output

	params := map[string]interface{}{
		"jobId": jobId,
	}
	if err := c.Do(ctx, xrpc.Query, "", "app.bsky.video.getJobStatus", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
