// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: app.bsky.video.abortUpload

package bsky

import (
	"context"

	lexutil "github.com/bluesky-social/indigo/lex/util"
)

// VideoAbortUpload_Input is the input argument to a app.bsky.video.abortUpload call.
type VideoAbortUpload_Input struct {
	JobId string `json:"jobId" cborgen:"jobId"`
}

// VideoAbortUpload_Output is the output of a app.bsky.video.abortUpload call.
type VideoAbortUpload_Output struct {
	// completedJobId: Present only when state is completed.
	CompletedJobId *string `json:"completedJobId,omitempty" cborgen:"completedJobId,omitempty"`
	// failureReason: Present only when state is failed.
	FailureReason *string `json:"failureReason,omitempty" cborgen:"failureReason,omitempty"`
	State         string  `json:"state" cborgen:"state"`
}

// VideoAbortUpload calls the XRPC method "app.bsky.video.abortUpload".
func VideoAbortUpload(ctx context.Context, c lexutil.LexClient, input *VideoAbortUpload_Input) (*VideoAbortUpload_Output, error) {
	var out VideoAbortUpload_Output
	if err := c.LexDo(ctx, lexutil.Procedure, "application/json", "app.bsky.video.abortUpload", nil, input, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
