// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: app.bsky.video.getJobStatus

package bsky

import (
	"context"

	lexutil "github.com/bluesky-social/indigo/lex/util"
)

// VideoGetJobStatus_Output is the output of a app.bsky.video.getJobStatus call.
type VideoGetJobStatus_Output struct {
	JobStatus *VideoDefs_JobStatus `json:"jobStatus" cborgen:"jobStatus"`
}

// VideoGetJobStatus calls the XRPC method "app.bsky.video.getJobStatus".
func VideoGetJobStatus(ctx context.Context, c lexutil.LexClient, jobId string) (*VideoGetJobStatus_Output, error) {
	var out VideoGetJobStatus_Output

	params := map[string]interface{}{}
	params["jobId"] = jobId
	if err := c.LexDo(ctx, lexutil.Query, "", "app.bsky.video.getJobStatus", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
