// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: tools.ozone.communication.listTemplates

package ozone

import (
	"context"

	lexutil "github.com/bluesky-social/indigo/lex/util"
)

// CommunicationListTemplates_Output is the output of a tools.ozone.communication.listTemplates call.
type CommunicationListTemplates_Output struct {
	CommunicationTemplates []*CommunicationDefs_TemplateView `json:"communicationTemplates" cborgen:"communicationTemplates"`
}

// CommunicationListTemplates calls the XRPC method "tools.ozone.communication.listTemplates".
func CommunicationListTemplates(ctx context.Context, c lexutil.LexClient) (*CommunicationListTemplates_Output, error) {
	var out CommunicationListTemplates_Output
	if err := c.LexDo(ctx, lexutil.Query, "", "tools.ozone.communication.listTemplates", nil, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
