// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: tools.ozone.moderation.getRecord

package ozone

import (
	"context"

	lexutil "github.com/bluesky-social/indigo/lex/util"
)

// ModerationGetRecord calls the XRPC method "tools.ozone.moderation.getRecord".
func ModerationGetRecord(ctx context.Context, c lexutil.LexClient, cid string, uri string) (*ModerationDefs_RecordViewDetail, error) {
	var out ModerationDefs_RecordViewDetail

	params := map[string]interface{}{}
	if cid != "" {
		params["cid"] = cid
	}
	params["uri"] = uri
	if err := c.LexDo(ctx, lexutil.Query, "", "tools.ozone.moderation.getRecord", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
