// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: tools.ozone.moderation.getRepo

package ozone

import (
	"context"

	lexutil "github.com/bluesky-social/indigo/lex/util"
)

// ModerationGetRepo calls the XRPC method "tools.ozone.moderation.getRepo".
func ModerationGetRepo(ctx context.Context, c lexutil.LexClient, did string) (*ModerationDefs_RepoViewDetail, error) {
	var out ModerationDefs_RepoViewDetail

	params := map[string]interface{}{}
	params["did"] = did
	if err := c.LexDo(ctx, lexutil.Query, "", "tools.ozone.moderation.getRepo", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
