// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: tools.ozone.queue.unassignModerator

package ozone

import (
	"context"

	lexutil "github.com/bluesky-social/indigo/lex/util"
)

// QueueUnassignModerator_Input is the input argument to a tools.ozone.queue.unassignModerator call.
type QueueUnassignModerator_Input struct {
	// did: DID to be unassigned.
	Did string `json:"did" cborgen:"did"`
	// queueId: The ID of the queue to unassign the user from.
	QueueId int64 `json:"queueId" cborgen:"queueId"`
}

// QueueUnassignModerator calls the XRPC method "tools.ozone.queue.unassignModerator".
func QueueUnassignModerator(ctx context.Context, c lexutil.LexClient, input *QueueUnassignModerator_Input) error {
	if err := c.LexDo(ctx, lexutil.Procedure, "application/json", "tools.ozone.queue.unassignModerator", nil, input, nil); err != nil {
		return err
	}

	return nil
}
