// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: tools.ozone.queue.createQueue

package ozone

import (
	"context"

	lexutil "github.com/bluesky-social/indigo/lex/util"
)

// QueueCreateQueue_Input is the input argument to a tools.ozone.queue.createQueue call.
type QueueCreateQueue_Input struct {
	// collection: Collection name for record subjects. Required if subjectTypes includes 'record'.
	Collection *string `json:"collection,omitempty" cborgen:"collection,omitempty"`
	// description: Optional description of the queue
	Description *string `json:"description,omitempty" cborgen:"description,omitempty"`
	// name: Display name for the queue (must be unique)
	Name string `json:"name" cborgen:"name"`
	// recommendedLabels: Labels to recommend for this queue and use as fallback appeal routing mappings
	RecommendedLabels []string `json:"recommendedLabels,omitempty" cborgen:"recommendedLabels,omitempty"`
	// recommendedPolicies: Policy keys to recommend when actioning reports in this queue
	RecommendedPolicies []string `json:"recommendedPolicies,omitempty" cborgen:"recommendedPolicies,omitempty"`
	// reportTypes: Report reason types (fully qualified NSIDs)
	ReportTypes []string `json:"reportTypes,omitempty" cborgen:"reportTypes,omitempty"`
	// subjectTypes: Subject types this queue accepts
	SubjectTypes []string `json:"subjectTypes,omitempty" cborgen:"subjectTypes,omitempty"`
}

// QueueCreateQueue_Output is the output of a tools.ozone.queue.createQueue call.
type QueueCreateQueue_Output struct {
	Queue *QueueDefs_QueueView `json:"queue" cborgen:"queue"`
}

// QueueCreateQueue calls the XRPC method "tools.ozone.queue.createQueue".
func QueueCreateQueue(ctx context.Context, c lexutil.LexClient, input *QueueCreateQueue_Input) (*QueueCreateQueue_Output, error) {
	var out QueueCreateQueue_Output
	if err := c.LexDo(ctx, lexutil.Procedure, "application/json", "tools.ozone.queue.createQueue", nil, input, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
