// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: tools.ozone.report.assignModerator

package ozone

import (
	"context"

	lexutil "github.com/bluesky-social/indigo/lex/util"
)

// ReportAssignModerator_Input is the input argument to a tools.ozone.report.assignModerator call.
type ReportAssignModerator_Input struct {
	// did: DID to be assigned. Defaults to the caller's DID. Admins may assign to any moderator.
	Did *string `json:"did,omitempty" cborgen:"did,omitempty"`
	// isPermanent: When true, the assignment has no expiry (endAt is null). Throws AlreadyAssigned if another user already has a permanent assignment on this report.
	IsPermanent *bool `json:"isPermanent,omitempty" cborgen:"isPermanent,omitempty"`
	// queueId: Optional queue ID to associate the assignment with. If not provided and the report has been assigned on a queue before, it will stay on that queue.
	QueueId *int64 `json:"queueId,omitempty" cborgen:"queueId,omitempty"`
	// reportId: The ID of the report to assign.
	ReportId int64 `json:"reportId" cborgen:"reportId"`
}

// ReportAssignModerator calls the XRPC method "tools.ozone.report.assignModerator".
func ReportAssignModerator(ctx context.Context, c lexutil.LexClient, input *ReportAssignModerator_Input) (*ReportDefs_AssignmentView, error) {
	var out ReportDefs_AssignmentView
	if err := c.LexDo(ctx, lexutil.Procedure, "application/json", "tools.ozone.report.assignModerator", nil, input, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
