// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: tools.ozone.report.listActivities

package ozone

import (
	"context"

	lexutil "github.com/bluesky-social/indigo/lex/util"
)

// ReportListActivities_Output is the output of a tools.ozone.report.listActivities call.
type ReportListActivities_Output struct {
	Activities []*ReportDefs_ReportActivityView `json:"activities" cborgen:"activities"`
	Cursor     *string                          `json:"cursor,omitempty" cborgen:"cursor,omitempty"`
}

// ReportListActivities calls the XRPC method "tools.ozone.report.listActivities".
//
// reportId: ID of the report whose activities to list
func ReportListActivities(ctx context.Context, c lexutil.LexClient, cursor string, limit int64, reportId int64) (*ReportListActivities_Output, error) {
	var out ReportListActivities_Output

	params := map[string]interface{}{}
	if cursor != "" {
		params["cursor"] = cursor
	}
	if limit != 0 {
		params["limit"] = limit
	}
	params["reportId"] = reportId
	if err := c.LexDo(ctx, lexutil.Query, "", "tools.ozone.report.listActivities", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
