// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: tools.ozone.report.queryActivities

package ozone

import (
	"context"

	lexutil "github.com/bluesky-social/indigo/lex/util"
)

// ReportQueryActivities_Output is the output of a tools.ozone.report.queryActivities call.
type ReportQueryActivities_Output struct {
	Activities []*ReportDefs_ReportActivityView `json:"activities" cborgen:"activities"`
	Cursor     *string                          `json:"cursor,omitempty" cborgen:"cursor,omitempty"`
}

// ReportQueryActivities calls the XRPC method "tools.ozone.report.queryActivities".
//
// activityTypes: Filter to specific activity types (e.g. closeActivity, escalationActivity). If omitted, all types are returned.
// createdAfter: Retrieve activities created at or after a given timestamp
// createdBefore: Retrieve activities created at or before a given timestamp
// cursor: Cursor of the form `<createdAtMs>::<activityId>`.
func ReportQueryActivities(ctx context.Context, c lexutil.LexClient, activityTypes []string, createdAfter string, createdBefore string, cursor string, limit int64, sortDirection string) (*ReportQueryActivities_Output, error) {
	var out ReportQueryActivities_Output

	params := map[string]interface{}{}
	if len(activityTypes) != 0 {
		params["activityTypes"] = activityTypes
	}
	if createdAfter != "" {
		params["createdAfter"] = createdAfter
	}
	if createdBefore != "" {
		params["createdBefore"] = createdBefore
	}
	if cursor != "" {
		params["cursor"] = cursor
	}
	if limit != 0 {
		params["limit"] = limit
	}
	if sortDirection != "" {
		params["sortDirection"] = sortDirection
	}
	if err := c.LexDo(ctx, lexutil.Query, "", "tools.ozone.report.queryActivities", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
