// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package ozone

// schema: tools.ozone.setting.removeOptions

import (
	"context"

	"github.com/bluesky-social/indigo/xrpc"
)

// SettingRemoveOptions_Input is the input argument to a tools.ozone.setting.removeOptions call.
type SettingRemoveOptions_Input struct {
	Keys  []string `json:"keys" cborgen:"keys"`
	Scope string   `json:"scope" cborgen:"scope"`
}

// SettingRemoveOptions_Output is the output of a tools.ozone.setting.removeOptions call.
type SettingRemoveOptions_Output struct {
}

// SettingRemoveOptions calls the XRPC method "tools.ozone.setting.removeOptions".
func SettingRemoveOptions(ctx context.Context, c *xrpc.Client, input *SettingRemoveOptions_Input) (*SettingRemoveOptions_Output, error) {
	var out SettingRemoveOptions_Output
	if err := c.Do(ctx, xrpc.Procedure, "application/json", "tools.ozone.setting.removeOptions", nil, input, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
