// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: tools.ozone.signature.findCorrelation

package ozone

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

// SignatureFindCorrelation_Output is the output of a tools.ozone.signature.findCorrelation call.
type SignatureFindCorrelation_Output struct {
	Details []*SignatureDefs_SigDetail `json:"details" cborgen:"details"`
}

// SignatureFindCorrelation calls the XRPC method "tools.ozone.signature.findCorrelation".
func SignatureFindCorrelation(ctx context.Context, c util.LexClient, dids []string) (*SignatureFindCorrelation_Output, error) {
	var out SignatureFindCorrelation_Output

	params := map[string]interface{}{}
	params["dids"] = dids
	if err := c.LexDo(ctx, util.Query, "", "tools.ozone.signature.findCorrelation", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
