FROM opensearchproject/opensearch:2.13.0
ARG OPENSEARCH_JAVA_OPTS
RUN /usr/share/opensearch/bin/opensearch-plugin install --batch analysis-icu
RUN /usr/share/opensearch/bin/opensearch-plugin install --batch analysis-kuromoji
