version: "3.8"
services:
  postgres:
    image: "postgres:14"
    ports:
      - "5432:5432"
    volumes:
      - type: bind
        source: /mnt/postgres
        target: /var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: bgs
      POSTGRES_PASSWORD: 33pAstcHDMszLedQah2EVYNgnxbCP
      POSTGRES_DB: bgs
