// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package atproto

// schema: com.atproto.admin.updateAccountPassword

import (
	"context"

	"github.com/gander-social/gander-indigo-sovereign/lex/util"
)

// AdminUpdateAccountPassword_Input is the input argument to a com.atproto.admin.updateAccountPassword call.
type AdminUpdateAccountPassword_Input struct {
	Did      string `json:"did" cborgen:"did"`
	Password string `json:"password" cborgen:"password"`
}

// AdminUpdateAccountPassword calls the XRPC method "com.atproto.admin.updateAccountPassword".
func AdminUpdateAccountPassword(ctx context.Context, c util.LexClient, input *AdminUpdateAccountPassword_Input) error {
	if err := c.LexDo(ctx, util.Procedure, "application/json", "com.atproto.admin.updateAccountPassword", nil, input, nil); err != nil {
		return err
	}

	return nil
}
