// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: com.atproto.admin.enableAccountInvites

package atproto

import (
	"context"

	lexutil "github.com/bluesky-social/indigo/lex/util"
)

// AdminEnableAccountInvites_Input is the input argument to a com.atproto.admin.enableAccountInvites call.
type AdminEnableAccountInvites_Input struct {
	Account string `json:"account" cborgen:"account"`
	// note: Optional reason for enabled invites.
	Note *string `json:"note,omitempty" cborgen:"note,omitempty"`
}

// AdminEnableAccountInvites calls the XRPC method "com.atproto.admin.enableAccountInvites".
func AdminEnableAccountInvites(ctx context.Context, c lexutil.LexClient, input *AdminEnableAccountInvites_Input) error {
	if err := c.LexDo(ctx, lexutil.Procedure, "application/json", "com.atproto.admin.enableAccountInvites", nil, input, nil); err != nil {
		return err
	}

	return nil
}
