// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: com.atproto.identity.refreshIdentity

package atproto

import (
	"context"

	lexutil "github.com/bluesky-social/indigo/lex/util"
)

// IdentityRefreshIdentity_Input is the input argument to a com.atproto.identity.refreshIdentity call.
type IdentityRefreshIdentity_Input struct {
	Identifier string `json:"identifier" cborgen:"identifier"`
}

// IdentityRefreshIdentity calls the XRPC method "com.atproto.identity.refreshIdentity".
func IdentityRefreshIdentity(ctx context.Context, c lexutil.LexClient, input *IdentityRefreshIdentity_Input) (*IdentityDefs_IdentityInfo, error) {
	var out IdentityDefs_IdentityInfo
	if err := c.LexDo(ctx, lexutil.Procedure, "application/json", "com.atproto.identity.refreshIdentity", nil, input, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
