// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package atproto

// schema: com.atproto.identity.resolveIdentity

import (
	"context"

	"github.com/bluesky-social/indigo/xrpc"
)

// IdentityResolveIdentity calls the XRPC method "com.atproto.identity.resolveIdentity".
//
// identifier: Handle or DID to resolve.
func IdentityResolveIdentity(ctx context.Context, c *xrpc.Client, identifier string) (*IdentityDefs_IdentityInfo, error) {
	var out IdentityDefs_IdentityInfo

	params := map[string]interface{}{
		"identifier": identifier,
	}
	if err := c.Do(ctx, xrpc.Query, "", "com.atproto.identity.resolveIdentity", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
