// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package atproto

// schema: com.atproto.label.defs

import (
	"github.com/bluesky-social/indigo/lex/util"
)

// LabelDefs_Label is a "label" in the com.atproto.label.defs schema.
//
// Metadata tag on an atproto resource (eg, repo or record)
type LabelDefs_Label struct {
	// cid: optionally, CID specifying the specific version of 'uri' resource this label applies to
	Cid *util.FormatCID `json:"cid,omitempty" cborgen:"cid,omitempty"`
	// cts: timestamp when this label was created
	Cts string `json:"cts" cborgen:"cts"`
	// neg: if true, this is a negation label, overwriting a previous label
	Neg *bool `json:"neg,omitempty" cborgen:"neg,omitempty"`
	// src: DID of the actor who created this label
	Src util.FormatDID `json:"src" cborgen:"src"`
	// uri: AT URI of the record, repository (account), or other resource which this label applies to
	Uri util.FormatURI `json:"uri" cborgen:"uri"`
	// val: the short string name of the value or type of this label
	Val string `json:"val" cborgen:"val"`
}
