// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: com.atproto.lexicon.resolveLexicon

package atproto

import (
	"context"

	lexutil "github.com/bluesky-social/indigo/lex/util"
)

// LexiconResolveLexicon_Output is the output of a com.atproto.lexicon.resolveLexicon call.
type LexiconResolveLexicon_Output struct {
	// cid: The CID of the lexicon schema record.
	Cid string `json:"cid" cborgen:"cid"`
	// schema: The resolved lexicon schema record.
	Schema *LexiconSchema `json:"schema" cborgen:"schema"`
	// uri: The AT-URI of the lexicon schema record.
	Uri string `json:"uri" cborgen:"uri"`
}

// LexiconResolveLexicon calls the XRPC method "com.atproto.lexicon.resolveLexicon".
//
// nsid: The lexicon NSID to resolve.
func LexiconResolveLexicon(ctx context.Context, c lexutil.LexClient, nsid string) (*LexiconResolveLexicon_Output, error) {
	var out LexiconResolveLexicon_Output

	params := map[string]interface{}{}
	params["nsid"] = nsid
	if err := c.LexDo(ctx, lexutil.Query, "", "com.atproto.lexicon.resolveLexicon", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
