// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package atproto

// schema: com.atproto.repo.defs

// RepoDefs_CommitMeta is a "commitMeta" in the com.atproto.repo.defs schema.
type RepoDefs_CommitMeta struct {
	Cid string `json:"cid" cborgen:"cid"`
	Rev string `json:"rev" cborgen:"rev"`
}
