// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package atproto

// schema: com.atproto.repo.rebaseRepo

import (
	"context"

	"github.com/bluesky-social/indigo/xrpc"
)

// RepoRebaseRepo_Input is the input argument to a com.atproto.repo.rebaseRepo call.
type RepoRebaseRepo_Input struct {
	// repo: The handle or DID of the repo.
	Repo string `json:"repo" cborgen:"repo"`
	// swapCommit: Compare and swap with the previous commit by cid.
	SwapCommit *string `json:"swapCommit,omitempty" cborgen:"swapCommit,omitempty"`
}

// RepoRebaseRepo calls the XRPC method "com.atproto.repo.rebaseRepo".
func RepoRebaseRepo(ctx context.Context, c *xrpc.Client, input *RepoRebaseRepo_Input) error {
	c.Mux.RLock()
	defer c.Mux.RUnlock()
	if err := c.Do(ctx, xrpc.Procedure, "application/json", "com.atproto.repo.rebaseRepo", nil, input, nil); err != nil {
		return err
	}

	return nil
}
