// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: com.atproto.server.resetPassword

package atproto

import (
	"context"

	lexutil "github.com/bluesky-social/indigo/lex/util"
)

// ServerResetPassword_Input is the input argument to a com.atproto.server.resetPassword call.
type ServerResetPassword_Input struct {
	Password string `json:"password" cborgen:"password"`
	Token    string `json:"token" cborgen:"token"`
}

// ServerResetPassword calls the XRPC method "com.atproto.server.resetPassword".
func ServerResetPassword(ctx context.Context, c lexutil.LexClient, input *ServerResetPassword_Input) error {
	if err := c.LexDo(ctx, lexutil.Procedure, "application/json", "com.atproto.server.resetPassword", nil, input, nil); err != nil {
		return err
	}

	return nil
}
