// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package atproto

// schema: com.atproto.server.requestAccountDelete

import (
	"context"

	"github.com/bluesky-social/indigo/xrpc"
)

// ServerRequestAccountDelete calls the XRPC method "com.atproto.server.requestAccountDelete".
func ServerRequestAccountDelete(ctx context.Context, c *xrpc.Client) error {
	if err := c.Do(ctx, xrpc.Procedure, "", "com.atproto.server.requestAccountDelete", nil, nil, nil); err != nil {
		return err
	}

	return nil
}
