// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package atproto

// schema: com.atproto.server.requestEmailUpdate

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

// ServerRequestEmailUpdate_Output is the output of a com.atproto.server.requestEmailUpdate call.
type ServerRequestEmailUpdate_Output struct {
	TokenRequired bool `json:"tokenRequired" cborgen:"tokenRequired"`
}

// ServerRequestEmailUpdate calls the XRPC method "com.atproto.server.requestEmailUpdate".
func ServerRequestEmailUpdate(ctx context.Context, c util.LexClient) (*ServerRequestEmailUpdate_Output, error) {
	var out ServerRequestEmailUpdate_Output
	if err := c.LexDo(ctx, util.Procedure, "", "com.atproto.server.requestEmailUpdate", nil, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
