// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: com.atproto.server.requestPasswordReset

package atproto

import (
	"context"

	lexutil "github.com/bluesky-social/indigo/lex/util"
)

// ServerRequestPasswordReset_Input is the input argument to a com.atproto.server.requestPasswordReset call.
type ServerRequestPasswordReset_Input struct {
	Email string `json:"email" cborgen:"email"`
}

// ServerRequestPasswordReset calls the XRPC method "com.atproto.server.requestPasswordReset".
func ServerRequestPasswordReset(ctx context.Context, c lexutil.LexClient, input *ServerRequestPasswordReset_Input) error {
	if err := c.LexDo(ctx, lexutil.Procedure, "application/json", "com.atproto.server.requestPasswordReset", nil, input, nil); err != nil {
		return err
	}

	return nil
}
