// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package atproto

// schema: com.atproto.server.activateAccount

import (
	"context"

	"github.com/bluesky-social/indigo/xrpc"
)

// ServerActivateAccount calls the XRPC method "com.atproto.server.activateAccount".
func ServerActivateAccount(ctx context.Context, c *xrpc.Client) error {
	if err := c.Do(ctx, xrpc.Procedure, "", "com.atproto.server.activateAccount", nil, nil, nil); err != nil {
		return err
	}

	return nil
}
