// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package atproto

// schema: com.atproto.server.deleteSession

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

// ServerDeleteSession calls the XRPC method "com.atproto.server.deleteSession".
func ServerDeleteSession(ctx context.Context, c util.LexClient) error {
	if err := c.LexDo(ctx, util.Procedure, "", "com.atproto.server.deleteSession", nil, nil, nil); err != nil {
		return err
	}

	return nil
}
