// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: com.atproto.sync.getCheckout

package atproto

import (
	"bytes"
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

// SyncGetCheckout calls the XRPC method "com.atproto.sync.getCheckout".
//
// did: The DID of the repo.
func SyncGetCheckout(ctx context.Context, c util.LexClient, did string) ([]byte, error) {
	buf := new(bytes.Buffer)

	params := map[string]interface{}{}
	params["did"] = did
	if err := c.LexDo(ctx, util.Query, "", "com.atproto.sync.getCheckout", params, nil, buf); err != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}
