// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package atproto

// schema: com.atproto.sync.requestCrawl

import (
	"context"

	"github.com/bluesky-social/indigo/xrpc"
)

// SyncRequestCrawl calls the XRPC method "com.atproto.sync.requestCrawl".
//
// hostname: Hostname of the service that is requesting to be crawled.
func SyncRequestCrawl(ctx context.Context, c *xrpc.Client, hostname string) error {

	params := map[string]interface{}{
		"hostname": hostname,
	}
	if err := c.Do(ctx, xrpc.Query, "", "com.atproto.sync.requestCrawl", params, nil, nil); err != nil {
		return err
	}

	return nil
}
