// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package atproto

// schema: com.atproto.temp.upgradeRepoVersion

import (
	"context"

	"github.com/bluesky-social/indigo/xrpc"
)

// TempUpgradeRepoVersion_Input is the input argument to a com.atproto.temp.upgradeRepoVersion call.
type TempUpgradeRepoVersion_Input struct {
	Did string `json:"did" cborgen:"did"`
}

// TempUpgradeRepoVersion calls the XRPC method "com.atproto.temp.upgradeRepoVersion".
func TempUpgradeRepoVersion(ctx context.Context, c *xrpc.Client, input *TempUpgradeRepoVersion_Input) error {
	if err := c.Do(ctx, xrpc.Procedure, "application/json", "com.atproto.temp.upgradeRepoVersion", nil, input, nil); err != nil {
		return err
	}

	return nil
}
