// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package atproto

// schema: com.atproto.temp.fetchLabels

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

// TempFetchLabels_Output is the output of a com.atproto.temp.fetchLabels call.
type TempFetchLabels_Output struct {
	Labels []*LabelDefs_Label `json:"labels" cborgen:"labels"`
}

// TempFetchLabels calls the XRPC method "com.atproto.temp.fetchLabels".
func TempFetchLabels(ctx context.Context, c util.LexClient, limit int64, since int64) (*TempFetchLabels_Output, error) {
	var out TempFetchLabels_Output

	params := map[string]interface{}{}
	if limit != 0 {
		params["limit"] = limit
	}
	if since != 0 {
		params["since"] = since
	}
	if err := c.LexDo(ctx, util.Query, "", "com.atproto.temp.fetchLabels", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
