// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package gndr

// schema: gndr.app.feed.getPosts

import (
	"context"

	"github.com/gander-social/gander-indigo-sovereign/lex/util"
)

// FeedGetPosts_Output is the output of a gndr.app.feed.getPosts call.
type FeedGetPosts_Output struct {
	Posts []*FeedDefs_PostView `json:"posts" cborgen:"posts"`
}

// FeedGetPosts calls the XRPC method "gndr.app.feed.getPosts".
//
// uris: List of post AT-URIs to return hydrated views for.
func FeedGetPosts(ctx context.Context, c util.LexClient, uris []string) (*FeedGetPosts_Output, error) {
	var out FeedGetPosts_Output

	params := map[string]interface{}{}
	params["uris"] = uris
	if err := c.LexDo(ctx, util.Query, "", "gndr.app.feed.getPosts", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
