// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package gndr

// schema: gndr.app.feed.getActorFeeds

import (
	"context"

	"github.com/gander-social/gander-indigo-sovereign/lex/util"
)

// FeedGetActorFeeds_Output is the output of a gndr.app.feed.getActorFeeds call.
type FeedGetActorFeeds_Output struct {
	Cursor *string                   `json:"cursor,omitempty" cborgen:"cursor,omitempty"`
	Feeds  []*FeedDefs_GeneratorView `json:"feeds" cborgen:"feeds"`
}

// FeedGetActorFeeds calls the XRPC method "gndr.app.feed.getActorFeeds".
func FeedGetActorFeeds(ctx context.Context, c util.LexClient, actor string, cursor string, limit int64) (*FeedGetActorFeeds_Output, error) {
	var out FeedGetActorFeeds_Output

	params := map[string]interface{}{}
	params["actor"] = actor
	if cursor != "" {
		params["cursor"] = cursor
	}
	if limit != 0 {
		params["limit"] = limit
	}
	if err := c.LexDo(ctx, util.Query, "", "gndr.app.feed.getActorFeeds", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
