// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package gndr

// schema: gndr.app.graph.getListMutes

import (
	"context"

	"github.com/gander-social/gander-indigo-sovereign/lex/util"
)

// GraphGetListMutes_Output is the output of a gndr.app.graph.getListMutes call.
type GraphGetListMutes_Output struct {
	Cursor *string               `json:"cursor,omitempty" cborgen:"cursor,omitempty"`
	Lists  []*GraphDefs_ListView `json:"lists" cborgen:"lists"`
}

// GraphGetListMutes calls the XRPC method "gndr.app.graph.getListMutes".
func GraphGetListMutes(ctx context.Context, c util.LexClient, cursor string, limit int64) (*GraphGetListMutes_Output, error) {
	var out GraphGetListMutes_Output

	params := map[string]interface{}{}
	if cursor != "" {
		params["cursor"] = cursor
	}
	if limit != 0 {
		params["limit"] = limit
	}
	if err := c.LexDo(ctx, util.Query, "", "gndr.app.graph.getListMutes", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
