// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package gndr

// schema: gndr.app.graph.getLists

import (
	"context"

	"github.com/gander-social/gander-indigo-sovereign/lex/util"
)

// GraphGetLists_Output is the output of a gndr.app.graph.getLists call.
type GraphGetLists_Output struct {
	Cursor *string               `json:"cursor,omitempty" cborgen:"cursor,omitempty"`
	Lists  []*GraphDefs_ListView `json:"lists" cborgen:"lists"`
}

// GraphGetLists calls the XRPC method "gndr.app.graph.getLists".
//
// actor: The account (actor) to enumerate lists from.
func GraphGetLists(ctx context.Context, c util.LexClient, actor string, cursor string, limit int64) (*GraphGetLists_Output, error) {
	var out GraphGetLists_Output

	params := map[string]interface{}{}
	params["actor"] = actor
	if cursor != "" {
		params["cursor"] = cursor
	}
	if limit != 0 {
		params["limit"] = limit
	}
	if err := c.LexDo(ctx, util.Query, "", "gndr.app.graph.getLists", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
