// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package gndr

// schema: gndr.app.graph.follow

import (
	"github.com/gander-social/gander-indigo-sovereign/lex/util"
)

func init() {
	util.RegisterType("gndr.app.graph.follow", &GraphFollow{})
} //
// RECORDTYPE: GraphFollow
type GraphFollow struct {
	LexiconTypeID string `json:"$type,const=gndr.app.graph.follow" cborgen:"$type,const=gndr.app.graph.follow"`
	CreatedAt     string `json:"createdAt" cborgen:"createdAt"`
	Subject       string `json:"subject" cborgen:"subject"`
}
