// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: chat.bsky.actor.exportAccountData

package chat

import (
	"bytes"
	"context"

	lexutil "github.com/bluesky-social/indigo/lex/util"
)

// ActorExportAccountData calls the XRPC method "chat.bsky.actor.exportAccountData".
func ActorExportAccountData(ctx context.Context, c lexutil.LexClient) ([]byte, error) {
	buf := new(bytes.Buffer)
	if err := c.LexDo(ctx, lexutil.Query, "", "chat.bsky.actor.exportAccountData", nil, nil, buf); err != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}
