// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: chat.bsky.actor.declaration

package chat

import (
	"github.com/bluesky-social/indigo/lex/util"
)

func init() {
	util.RegisterType("chat.bsky.actor.declaration", &ActorDeclaration{})
}

type ActorDeclaration struct {
	LexiconTypeID string `json:"$type" cborgen:"$type,const=chat.bsky.actor.declaration"`
	AllowIncoming string `json:"allowIncoming" cborgen:"allowIncoming"`
}
