// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package chat

// schema: chat.bsky.actor.deleteAccount

import (
	"context"

	"github.com/bluesky-social/indigo/xrpc"
)

// ActorDeleteAccount_Output is the output of a chat.bsky.actor.deleteAccount call.
type ActorDeleteAccount_Output struct {
}

// ActorDeleteAccount calls the XRPC method "chat.bsky.actor.deleteAccount".
func ActorDeleteAccount(ctx context.Context, c *xrpc.Client) (*ActorDeleteAccount_Output, error) {
	var out ActorDeleteAccount_Output
	if err := c.Do(ctx, xrpc.Procedure, "", "chat.bsky.actor.deleteAccount", nil, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
