// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package chat

// schema: chat.bsky.convo.unmuteConvo

import (
	"context"

	"github.com/bluesky-social/indigo/xrpc"
)

// ConvoUnmuteConvo_Input is the input argument to a chat.bsky.convo.unmuteConvo call.
type ConvoUnmuteConvo_Input struct {
	ConvoId string `json:"convoId" cborgen:"convoId"`
}

// ConvoUnmuteConvo_Output is the output of a chat.bsky.convo.unmuteConvo call.
type ConvoUnmuteConvo_Output struct {
	Convo *ConvoDefs_ConvoView `json:"convo" cborgen:"convo"`
}

// ConvoUnmuteConvo calls the XRPC method "chat.bsky.convo.unmuteConvo".
func ConvoUnmuteConvo(ctx context.Context, c *xrpc.Client, input *ConvoUnmuteConvo_Input) (*ConvoUnmuteConvo_Output, error) {
	var out ConvoUnmuteConvo_Output
	if err := c.Do(ctx, xrpc.Procedure, "application/json", "chat.bsky.convo.unmuteConvo", nil, input, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
