// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: chat.bsky.convo.lockConvo

package chat

import (
	"context"

	lexutil "github.com/bluesky-social/indigo/lex/util"
)

// ConvoLockConvo_Input is the input argument to a chat.bsky.convo.lockConvo call.
type ConvoLockConvo_Input struct {
	ConvoId string `json:"convoId" cborgen:"convoId"`
}

// ConvoLockConvo_Output is the output of a chat.bsky.convo.lockConvo call.
type ConvoLockConvo_Output struct {
	Convo *ConvoDefs_ConvoView `json:"convo" cborgen:"convo"`
}

// ConvoLockConvo calls the XRPC method "chat.bsky.convo.lockConvo".
func ConvoLockConvo(ctx context.Context, c lexutil.LexClient, input *ConvoLockConvo_Input) (*ConvoLockConvo_Output, error) {
	var out ConvoLockConvo_Output
	if err := c.LexDo(ctx, lexutil.Procedure, "application/json", "chat.bsky.convo.lockConvo", nil, input, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
