// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package chat

// schema: chat.gndr.convo.leaveConvo

import (
	"context"

	"github.com/gander-social/gander-indigo-sovereign/lex/util"
)

// ConvoLeaveConvo_Input is the input argument to a chat.gndr.convo.leaveConvo call.
type ConvoLeaveConvo_Input struct {
	ConvoId string `json:"convoId" cborgen:"convoId"`
}

// ConvoLeaveConvo_Output is the output of a chat.gndr.convo.leaveConvo call.
type ConvoLeaveConvo_Output struct {
	ConvoId string `json:"convoId" cborgen:"convoId"`
	Rev     string `json:"rev" cborgen:"rev"`
}

// ConvoLeaveConvo calls the XRPC method "chat.gndr.convo.leaveConvo".
func ConvoLeaveConvo(ctx context.Context, c util.LexClient, input *ConvoLeaveConvo_Input) (*ConvoLeaveConvo_Output, error) {
	var out ConvoLeaveConvo_Output
	if err := c.LexDo(ctx, util.Procedure, "application/json", "chat.gndr.convo.leaveConvo", nil, input, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
