// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package chat

// schema: chat.bsky.convo.deleteMessageForSelf

import (
	"context"

	"github.com/bluesky-social/indigo/xrpc"
)

// ConvoDeleteMessageForSelf_Input is the input argument to a chat.bsky.convo.deleteMessageForSelf call.
type ConvoDeleteMessageForSelf_Input struct {
	ConvoId   string `json:"convoId" cborgen:"convoId"`
	MessageId string `json:"messageId" cborgen:"messageId"`
}

// ConvoDeleteMessageForSelf calls the XRPC method "chat.bsky.convo.deleteMessageForSelf".
func ConvoDeleteMessageForSelf(ctx context.Context, c *xrpc.Client, input *ConvoDeleteMessageForSelf_Input) (*ConvoDefs_DeletedMessageView, error) {
	var out ConvoDefs_DeletedMessageView
	if err := c.Do(ctx, xrpc.Procedure, "application/json", "chat.bsky.convo.deleteMessageForSelf", nil, input, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
