// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: chat.bsky.convo.getUnreadCounts

package chat

import (
	"context"

	lexutil "github.com/bluesky-social/indigo/lex/util"
)

// ConvoGetUnreadCounts_Output is the output of a chat.bsky.convo.getUnreadCounts call.
type ConvoGetUnreadCounts_Output struct {
	// unreadAcceptedConvos: Number of unread, unlocked accepted convos. Counts convos with unread messages and unread join requests. Capped at 100, where 100 means more than 99.
	UnreadAcceptedConvos int64 `json:"unreadAcceptedConvos" cborgen:"unreadAcceptedConvos"`
	// unreadRequestConvos: Number of unread, unlocked request convos. Includes convos with unread messages, but not with unread join request, since only the owner of a group has join requests to read, and the group would necessarily be accepted. Capped at 100, where 100 means more than 99.
	UnreadRequestConvos int64 `json:"unreadRequestConvos" cborgen:"unreadRequestConvos"`
}

// ConvoGetUnreadCounts calls the XRPC method "chat.bsky.convo.getUnreadCounts".
//
// includeGroupChats: When false, group convos are excluded from the counts.
func ConvoGetUnreadCounts(ctx context.Context, c lexutil.LexClient, includeGroupChats bool) (*ConvoGetUnreadCounts_Output, error) {
	var out ConvoGetUnreadCounts_Output

	params := map[string]interface{}{}
	if includeGroupChats {
		params["includeGroupChats"] = includeGroupChats
	}
	if err := c.LexDo(ctx, lexutil.Query, "", "chat.bsky.convo.getUnreadCounts", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
