// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package chat

// schema: chat.gndr.convo.getConvo

import (
	"context"

	"github.com/gander-social/gander-indigo-sovereign/lex/util"
)

// ConvoGetConvo_Output is the output of a chat.gndr.convo.getConvo call.
type ConvoGetConvo_Output struct {
	Convo *ConvoDefs_ConvoView `json:"convo" cborgen:"convo"`
}

// ConvoGetConvo calls the XRPC method "chat.gndr.convo.getConvo".
func ConvoGetConvo(ctx context.Context, c util.LexClient, convoId string) (*ConvoGetConvo_Output, error) {
	var out ConvoGetConvo_Output

	params := map[string]interface{}{}
	params["convoId"] = convoId
	if err := c.LexDo(ctx, util.Query, "", "chat.gndr.convo.getConvo", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
