// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: chat.bsky.group.enableJoinLink

package chat

import (
	"context"

	lexutil "github.com/bluesky-social/indigo/lex/util"
)

// GroupEnableJoinLink_Input is the input argument to a chat.bsky.group.enableJoinLink call.
type GroupEnableJoinLink_Input struct {
	ConvoId string `json:"convoId" cborgen:"convoId"`
}

// GroupEnableJoinLink_Output is the output of a chat.bsky.group.enableJoinLink call.
type GroupEnableJoinLink_Output struct {
	JoinLink *GroupDefs_JoinLinkView `json:"joinLink" cborgen:"joinLink"`
}

// GroupEnableJoinLink calls the XRPC method "chat.bsky.group.enableJoinLink".
func GroupEnableJoinLink(ctx context.Context, c lexutil.LexClient, input *GroupEnableJoinLink_Input) (*GroupEnableJoinLink_Output, error) {
	var out GroupEnableJoinLink_Output
	if err := c.LexDo(ctx, lexutil.Procedure, "application/json", "chat.bsky.group.enableJoinLink", nil, input, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
