// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: chat.bsky.group.updateJoinRequestsRead

package chat

import (
	"context"

	lexutil "github.com/bluesky-social/indigo/lex/util"
)

// GroupUpdateJoinRequestsRead_Input is the input argument to a chat.bsky.group.updateJoinRequestsRead call.
type GroupUpdateJoinRequestsRead_Input struct {
	ConvoId string `json:"convoId" cborgen:"convoId"`
}

// GroupUpdateJoinRequestsRead_Output is the output of a chat.bsky.group.updateJoinRequestsRead call.
type GroupUpdateJoinRequestsRead_Output struct {
}

// GroupUpdateJoinRequestsRead calls the XRPC method "chat.bsky.group.updateJoinRequestsRead".
func GroupUpdateJoinRequestsRead(ctx context.Context, c lexutil.LexClient, input *GroupUpdateJoinRequestsRead_Input) (*GroupUpdateJoinRequestsRead_Output, error) {
	var out GroupUpdateJoinRequestsRead_Output
	if err := c.LexDo(ctx, lexutil.Procedure, "application/json", "chat.bsky.group.updateJoinRequestsRead", nil, input, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
