// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: chat.bsky.group.getGroupPublicInfo

package chat

import (
	"context"

	lexutil "github.com/bluesky-social/indigo/lex/util"
)

// GroupGetGroupPublicInfo_Output is the output of a chat.bsky.group.getGroupPublicInfo call.
type GroupGetGroupPublicInfo_Output struct {
	Group *GroupDefs_GroupPublicView `json:"group" cborgen:"group"`
}

// GroupGetGroupPublicInfo calls the XRPC method "chat.bsky.group.getGroupPublicInfo".
func GroupGetGroupPublicInfo(ctx context.Context, c lexutil.LexClient, code string) (*GroupGetGroupPublicInfo_Output, error) {
	var out GroupGetGroupPublicInfo_Output

	params := map[string]interface{}{}
	params["code"] = code
	if err := c.LexDo(ctx, lexutil.Query, "", "chat.bsky.group.getGroupPublicInfo", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
