// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: chat.bsky.group.createGroup

package chat

import (
	"context"

	lexutil "github.com/bluesky-social/indigo/lex/util"
)

// GroupCreateGroup_Input is the input argument to a chat.bsky.group.createGroup call.
type GroupCreateGroup_Input struct {
	// members: The members to add to the group. The owner is automatically added. Implementations may enforce a lower maximum than the 10,000-item schema limit; Bluesky currently supports up to 100 total members. If the owner is included in this list, the list may contain up to the implementation's total member limit. Otherwise, it may contain one fewer.
	Members []string `json:"members" cborgen:"members"`
	Name    string   `json:"name" cborgen:"name"`
}

// GroupCreateGroup_Output is the output of a chat.bsky.group.createGroup call.
type GroupCreateGroup_Output struct {
	Convo *ConvoDefs_ConvoView `json:"convo" cborgen:"convo"`
}

// GroupCreateGroup calls the XRPC method "chat.bsky.group.createGroup".
func GroupCreateGroup(ctx context.Context, c lexutil.LexClient, input *GroupCreateGroup_Input) (*GroupCreateGroup_Output, error) {
	var out GroupCreateGroup_Output
	if err := c.LexDo(ctx, lexutil.Procedure, "application/json", "chat.bsky.group.createGroup", nil, input, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
